.TH "cmemit" 1 "@RELEASEDATE@" "@PACKAGE@ @RELEASE@" "@PACKAGE@ Manual"

.SH NAME
.TP 
cmemit - generate sequences from a covariance model

.SH SYNOPSIS
.B cmemit
.I [options]
.I cmfile
.I seqfile

.SH DESCRIPTION

.B cmemit
reads the first covariance model (CM) in
.I cmfile
and generates a number of sequences from the CM;
or if the -c option is selected, generates a single majority-fule
consensus. This can be useful for various application in which one
needs a simulation of sequences consistent with a sequence family
consensus. By default,
.B cmemit 
generates 10 sequences and outputs them in FASTA (unaligned) format.

.SH OPTIONS

.TP
.B -a
Write the generated sequences in an aligned format (STOCKHOLM) with
consensus structure annotation rather than FASTA. 

.TP
.B -c
Predict a single majority-rule consensus sequence instead of sampling
sequences from the CM’s probability distribution. Highly conserved
residues are shown in upper case; others are shown in lower
case.

.TP
.B -h
Print brief help; includes version number and summary of
all options, including expert options.

.TP
.BI -n " <n>"
Generate 
.I <n>
sequences. Default is 10. 

.TP
.BI -o " <f>" 
Save the synthetic sequences to file 
.I <f> 
rather than writing them to stdout. 

.TP
.B -q 
Quiet; suppress all output except for the sequences
themselves. Useful for piping or directing the output.

.SH EXPERT OPTIONS

.TP
.BI --seed " <n>"
Set the random seed to 
.I <n>, 
where <n> is a positive integer. The default is to use time() to
generate a different seed for each run, which means that two different
runs of cmmemit on the same CM will give slightly different
results. You can use this option to generate reproducible results.

.TP
.BI --begin " <n>"
Truncate the resulting alignment by beginning at match column 
.I <n>,
where <n> is a positive integer no greater than the consensus length of
the CM. Must be used in combination with --end and either -a or --cp9.

.TP
.BI --end " <n>"
Truncate the resulting alignment by ending at match column 
.I <n>,
where <n> is a positive integer no greater than the consensus length of
the CM. Must be used in combination with --begin and either -a or --cp9.

.TP
.BI --cp9 " <n>"
Use the generated sequences to train a CM Plan 9 maximum-likelihood
HMM without using pseudo-counts. Print the counts and normalized
probabilities of the HMM. Primarily useful for debugging.






