.TH "cmscore" 1 @RELEASEDATE@ "@PACKAGE@" "@PACKAGE@ Manual"

.SH NAME
.TP 
cmscore - align and score one or more sequences to a CM

.SH SYNOPSIS
.B cmscore
.I [options]
.I cmfile
.I seqfile

.SH DESCRIPTION

.B cmscore
uses the
covariance model (CM) in
.I cmfile
to align and score the sequences in
.I seqfile,
and output the score and optimal alignment for each one.
.B cmscore 
is a testbed 
for new CM alignment algorithms, and
is not intended to be particularly useful in the real world. Documentation
is provided for completeness... and to aid my own memory.

.PP
Currently, 
.B cmscore
aligns the sequence(s) by both the full CYK algorithm and
the divide and conquer variant (SR Eddy, BMC Bioinformatics 3:18,
2002), and outputs both parse trees; these should be identical
for any sequence.

.PP
The sequence file can be in most any common biosequence format,
including alignment file formats (in which case the sequences
will be read as if they were unaligned). FASTA format is
recommended. 

.PP
The sequences are treated as single stranded RNAs; that is,
only the given strand of each sequence is aligned and scored, and
no reverse complementing is done.

.PP
CM files are profiles of RNA consensus secondary structure. A
CM file is produced by the 
.B cmbuild 
program, from a given RNA sequence alignment of known 
consensus structure.

.SH OPTIONS

.TP
.B -h
Print brief help; includes version number and summary of
all options, including expert options.

.SH EXPERT OPTIONS

.TP
.BI --informat " <s>"
Assert that the input 
.I seqfile
is in format
.I <s>.
Do not run Babelfish format autodection. This increases
the reliability of the program somewhat, because 
the Babelfish can make mistakes; particularly
recommended for unattended, high-throughput runs
of @PACKAGE@. 
.I <s>
is case-insensitive;
valid formats include FASTA,
GENBANK, EMBL, GCG, PIR, STOCKHOLM, SELEX, MSF,
CLUSTAL, and PHYLIP. 
See the User's Guide for a complete
list.

.TP
.B --local
Turn on the local alignment algorithm, which allows the alignment
to span two or more subsequences if necessary (e.g. if the structures
of the query model and target sequence are only partially shared),
allowing certain large insertions and deletions in the structure
to be penalized differently than normal indels.
The default is to globally align the query model to the target
sequences.

.TP
.BI --regress " <f>"
Save regression test information to a file
.I <f>. 
This is part of the automated testing procedure at each release. 

.TP
.B --scoreonly
Do the small memory "score only" variant of the standard CYK alignment
algorithm, and don't recover a parse tree. 

.TP
.B --smallonly
Skip the standard CYK algorithm; do only the divide and conquer
algorithm.

.TP
.B --stringent
Require the two parse trees to be identical; fail and return a
non-zero exit code if they are not.

.TP 
.B --X
Project X. Undocumented. No serviceable parts inside.
Using this option voids your warranty. Do not attempt.
Professional driver on a closed course. May induce
dizziness and vomiting.





