.TH "cmstat" 1 "@INFERNAL_DATE@" "INFERNAL @INFERNAL_VERSION@" "INFERNAL Manual"

.SH NAME
.TP 
cmstat - display summary statistics for a CM

.SH SYNOPSIS
.B cmstat
.I [options]
.I cmfile

.SH DESCRIPTION

.B cmstat
calculates and displays various types of statistics describing the 
covariance models (CMs) in
.I cmfile. 

By default,
.B cmstat
prints general statistics of the model and the alignment it was built
from. Additionally, if the model(s) in 
.I cmfile
have been calibrated with 
.B cmcalibrate
the 
.B -E,
.B -T,
and 
.BI -Z " <n>"
options can be used to display E-values and corresponding bit scores
for a specified database size of
.I <n> 
megabases (Mb). If the model(s) have been calibrated and
include Rfam GA, TC, and/or NC bit score thresholds the 
.B --cut_ga,
.B --cut_tc,
and/or
.B --cut_nc 
options can be used to display E-values that correspond to the bit
score thresholds. Seperate bit scores or E-values will be displayed
for each of the four possible CM search algorithm and model
configuration pairs: local Inside, local CYK, glocal Inside and glocal
CYK.

.SH OPTIONS

.TP
.B -h
Help; print a brief reminder of command line usage and all available
options.

.TP
.BI -E " <x1>"
Report bit scores that correspond to an E-value of 
.I <x1> 
in a database of 
.I <x> 
megabases (Mb), where 
.I <x>
is 10 by default but settable with the 
.BI -Z " <x>"
option. 

.TP
.BI -T " <x1>"
Report E-values that correspond to a bit score of
.I <x1> 
in a database of 
.I <x> 
megabases (Mb), where 
.I <x>
is 10 by default but settable with the 
.BI -Z " <x>"
option. 

.TP
.BI -Z " <x>"
With the 
.B -E, 
.B -T,
.B --cut_ga,
.B --cut_nc, 
and
.B --cut_tc
options, calculate E-values as if the target database size was 
.I <x> 
megabases (Mb). By default, 
.I <x>
is 10.

.TP
.B --cut_ga
Report E-values that correspond to the GA (Rfam gathering threshold) 
bit score 
in a database of 
.I <x> 
megabases (Mb), where 
.I <x>
is 10 by default but settable with the 
.BI -Z " <x>"
option. 

.TP
.B --cut_tc
Report E-values that correspond to the TC (Rfam trusted cutoff)
bit score 
in a database of 
.I <x> 
megabases (Mb), where 
.I <x>
is 10 by default but settable with the 
.BI -Z " <x>"
option. 

.TP
.B --cut_nc
Report E-values that correspond to the NC (Rfam noise cutoff)
bit score 
in a database of 
.I <x> 
megabases (Mb), where 
.I <x>
is 10 by default but settable with the 
.BI -Z " <x>"
option. 

.TP
.BI --key " <s>"
Only print statistics for CM with name or accession 
.I <s>,
skip all other models in 
.I <cmfile>.

.SH SEE ALSO 

See 
.B infernal(1)
for a master man page with a list of all the individual man pages
for programs in the INFERNAL package.

.PP
For complete documentation, see the user guide that came with your
INFERNAL distribution (Userguide.pdf); or see the INFERNAL web page
(@INFERNAL_URL@).


.SH COPYRIGHT

.nf
@INFERNAL_COPYRIGHT@
@INFERNAL_LICENSE@
.fi

For additional information on copyright and licensing, see the file
called COPYRIGHT in your INFERNAL source distribution, or see the INFERNAL
web page 
(@INFERNAL_URL@).

.SH AUTHOR

.nf
The Eddy/Rivas Laboratory
Janelia Farm Research Campus
19700 Helix Drive
Ashburn VA 20147 USA
http://eddylab.org
.fi



