#! /usr/bin/perl

# bug i6 - local D&C score/parsetree score discrepancy
# EPN, Mon Nov  6 13:27:10 2006
#
# CYKDivideAndConquer() reports scores that don't match
# the parsetree score; in all observed cases this involves 
# EL states.

#
# i6.1 =  simple example alignment (1 seq) from user's guide
# i6.2 =  a short sequence (found by trial and error) that 
#         causes an instance of the bug
# 

$usage = "i6 <cmbuild> <cmscore>\n";
if ($#ARGV != 1) { die "Wrong argument number.\n$usage"; }

$cmbuild  = shift;
$cmscore  = shift;
$ok       = 1;

# Make our test alignment file, i6.1
#
open (OUT, ">i6.1") || die;
print OUT <<END;
# STOCKHOLM 1.0

human              AAGACUUCGGAUCUGGCGACACCC
#=GC SS_cons       ::<<<____>->>:<<-<___>>>
#=GC RF            xxxxxxxxxxxxxxxxxxxxxxxx
//
END
close OUT;

# Make our test sequence file, i6.2
#
open (OUT, ">i6.2") || die;
print OUT <<END;
>seq
GUGACGAUCAAUUU
END
close OUT;

if ($ok) { 
    system("$cmbuild -F --rf i6.cm i6.1 > /dev/null 2> /dev/null");
    if ($? != 0) { $ok = 0; }
}
if ($ok) {
    system("$cmscore --local i6.cm i6.2 > /dev/null 2> /dev/null");
    if ($? != 0) { $ok = 0; }
}

foreach $tmpfile ("i6.1", "i6.2", "i6.cm") {
    unlink $tmpfile if -e $tmpfile;
}

if ($ok) { print "ok\n";     exit 0; }
else     { print "FAILED\n"; exit 1; }


