.TH "cmsearch_dual" 1 "@RELEASEDATE@" "@PACKAGE@ @RELEASE@" "@PACKAGE@ Manual"

.SH NAME
.TP
cmsearch_dual - search a sequence database for RNAs homologous to a CM using two filtering pipelines

.SH SYNOPSIS
.B cmsearch_dual
.I [options]
.I cmfile
.I seqfile

.SH DESCRIPTION
.B cmsearch_dual
uses the covariance model (CM) in
.I cmfile
to search for homologous RNAs in 
.I seqfile,
and outputs high-scoring alignments.
.B cmsearch_dual
runs both the standard filter pipeline of 
.B cmsearch
and the structure-based filter pipeline of 
.B sse_cmsearch
and combines the results in a single, sorted
results list.

.PP
Currently, the sequence file must be in FASTA format.

.PP
CMs are profiles of RNA consensus sequence and secondary structure. A
CM file is produced by the 
.B cmbuild 
program, from a given RNA sequence alignment of known 
consensus structure.
CM files must be calibrated prior to running 
.B cmsearch_dual
with the 
.B cmcalibrate 
program. Searches with calibrated CM files will include
E-values and will use appropriate filter thresholds for
acceleration. 
CM calibration is described in more detail 
in chapters 5 and 6 of the User's Guide.

.PP
.B cmsearch_dual
output is in the same format used by 
.B cmsearch;
consult the User's Guide for more detail.

.SH OPTIONS

.TP
.B --help
Print brief help, including summary of available options.

.TP
.BI -Z " <x>"
Calculate E-values as if the target database size was 
.I <x> 
megabases (Mb). Ignore the actual size of the sequence file.

.TP 
.B -P <n>
Directly specify the path 
.I <n>
to 
.B cmsearch.
This is unecessary if 
.B cmsearch
is installed and available in your path.

.TP 
.B -Q <n>
Directly specify the path 
.I <n>
to 
.B sse_cmsearch.
This is unecessary if 
.B sse_cmsearch
is installed and available in your path.

.TP 
.B -R <n>
Directly specify the path 
.I <n>
to 
.B esl-sfetch.
This is unecessary if 
.B esl-sfetch
is installed and available in your path.

