/* cm_fast_calibrate.c
 * Fast CM calibration via ridge regression on compiled-in JSON models.
 *
 * Phase 1: JSON parsing, model loading, and print_models() debug helper.
 * cm_FastCalibrate() is a stub returning eslFAIL (real prediction: Phase 4).
 *
 * JSON layout (two schemas):
 *   v4.1 (STR tiny/small/medlarge):
 *     modes[mode]["STR"][bucket]   → ridge {alpha, loo_mse, coef_z, feature_mean, feature_std, target_mean, n_train}
 *                                    features list is at top-level schema["STR_features"]
 *   v4.2 (STR large/huge, NOSS tiny/small/medlarge):
 *     lambda[bucket][mode]         → ridge {features, feature_mean, feature_std, coef_z, target_mean, alpha, loo_mse}
 *     mu_extrap[bucket][mode]      → ridge (same)
 *     mu_orig[bucket][mode]        → ridge (same)
 *
 * Model mapping:
 *   production_models_v41.json        → g_models.str_lambda    [0..2][*]   (buckets tiny/small/medlarge)
 *   production_mu_models_v41.json     → g_models.str_mu_extrap [0..2][*]
 *                                     → g_models.str_mu_orig   [0..2][*]
 *   production_models_v42_largehuge   → g_models.str_lambda    [3..4][*]   (buckets large/huge)
 *   production_mu_models_v42_largehuge→ g_models.str_mu_extrap [3..4][*]
 *                                     → g_models.str_mu_orig   [3..4][*]
 *   production_models_v42_noss        → g_models.noss_lambda   [0..2][*]
 *   production_mu_models_v42_noss     → g_models.noss_mu_extrap[0..2][*]
 *                                     → g_models.noss_mu_orig  [0..2][*]
 *
 * See: CPORT_SPEC.md §3-5.
 */

#include "esl_config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "easel.h"
#include "esl_buffer.h"
#include "esl_json.h"

#include "infernal.h"
#include "cm_fast_calibrate.h"

/* Embedded JSON data arrays (generated by embed_fastcal_models.sh via xxd -i) */
#include "cm_fast_calibrate_models.h"

/* =========================================================================
 * Internal constants
 */

#define N_BUCKETS  5   /* tiny=0, small=1, medlarge=2, large=3, huge=4    */
#define N_MODES    4   /* ECMLC=0, ECMLI=1, ECMGC=2, ECMGI=3             */

/* Bucket indices */
#define BUCKET_TINY      0
#define BUCKET_SMALL     1
#define BUCKET_MEDLARGE  2
#define BUCKET_LARGE     3
#define BUCKET_HUGE      4

/* Mode indices */
#define MODE_ECMLC  0
#define MODE_ECMLI  1
#define MODE_ECMGC  2
#define MODE_ECMGI  3

/* =========================================================================
 * Data structures
 */

typedef struct {
  int      nfeat;      /* number of features; 0 = slot unused                */
  char   **fnames;     /* feature name strings [nfeat], NULL-terminated list  */
  double  *mean;       /* feature_mean[nfeat]                                  */
  double  *std;        /* feature_std[nfeat]                                   */
  double  *coef;       /* coef_z[nfeat]                                        */
  double   intercept;  /* target_mean                                          */
  double   loo_mse;    /* informational only                                   */
} FastCalRidge;

typedef struct {
  FastCalRidge str_lambda    [N_BUCKETS][N_MODES];
  FastCalRidge str_mu_extrap [N_BUCKETS][N_MODES];
  FastCalRidge str_mu_orig   [N_BUCKETS][N_MODES];
  FastCalRidge noss_lambda   [N_BUCKETS][N_MODES];
  FastCalRidge noss_mu_extrap[N_BUCKETS][N_MODES];
  FastCalRidge noss_mu_orig  [N_BUCKETS][N_MODES];
  char         models_version[65];   /* SHA-256 hex of concatenated JSONs + NUL */
  int          loaded;
} FastCalModelSet;

static FastCalModelSet g_models;   /* zero-initialised by C spec */


/* =========================================================================
 * Internal helper: free a single ridge
 */
static void
ridge_free(FastCalRidge *r)
{
  if (r == NULL || r->nfeat == 0) return;
  if (r->fnames) {
    int i;
    for (i = 0; i < r->nfeat; i++) free(r->fnames[i]);
    free(r->fnames);
    r->fnames = NULL;
  }
  if (r->mean) { free(r->mean); r->mean = NULL; }
  if (r->std)  { free(r->std);  r->std  = NULL; }
  if (r->coef) { free(r->coef); r->coef = NULL; }
  r->nfeat = 0;
}


/* =========================================================================
 * Internal helper: parse a double from a JSON number token
 *   esl_json_ReadFloat only returns float; we need double precision.
 */
static double
json_tok_to_double(ESL_JSON *pi, int idx, ESL_BUFFER *bf)
{
  char     *p   = esl_json_GetMem(pi, idx, bf);
  esl_pos_t n   = esl_json_GetLen(pi, idx, bf);
  char      buf[64];
  if (n >= 63) n = 62;
  memcpy(buf, p, (size_t)n);
  buf[n] = '\0';
  return strtod(buf, NULL);
}


/* =========================================================================
 * Internal helper: check if a KEY token matches a string
 */
static int
key_matches(ESL_JSON *pi, int idx, ESL_BUFFER *bf, const char *want)
{
  char     *p  = esl_json_GetMem(pi, idx, bf);
  esl_pos_t n  = esl_json_GetLen(pi, idx, bf);
  size_t    wn = strlen(want);
  if ((size_t)n != wn) return 0;
  return (memcmp(p, want, wn) == 0);
}


/* =========================================================================
 * Internal helper: find the first child of an object/array with a KEY
 * that matches <keyname>. Returns the index of the VALUE (not the key).
 * Returns -1 if not found.
 */
static int
json_find_key(ESL_JSON *pi, ESL_BUFFER *bf, int obj_idx, const char *keyname)
{
  int c;
  if (pi->tok[obj_idx].type != eslJSON_OBJECT) return -1;
  for (c = pi->tok[obj_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    {
      /* In esl_json, obj children are alternating key/value.
       * Each "child" is a key; its value is key->nextsib. */
      if (pi->tok[c].type == eslJSON_KEY && key_matches(pi, c, bf, keyname))
        return pi->tok[c].nextsib;   /* value follows the key in the sibling list */
    }
  return -1;
}


/* =========================================================================
 * Internal helper: parse a double[] array from a JSON ARRAY token.
 * Allocates *ret_arr (caller frees). Returns number of elements.
 */
static int
parse_double_array(ESL_JSON *pi, ESL_BUFFER *bf, int arr_idx, double **ret_arr)
{
  int     n, c, i;
  int     status;
  double *arr;

  if (pi->tok[arr_idx].type != eslJSON_ARRAY) { *ret_arr = NULL; return 0; }
  n = pi->tok[arr_idx].nchild;
  if (n == 0) { *ret_arr = NULL; return 0; }

  ESL_ALLOC(arr, sizeof(double) * n);
  i = 0;
  for (c = pi->tok[arr_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    arr[i++] = json_tok_to_double(pi, c, bf);

  *ret_arr = arr;
  return n;

 ERROR:
  *ret_arr = NULL;
  return 0;
}


/* =========================================================================
 * Internal helper: parse a string[] array from a JSON ARRAY token.
 * Returns nfeat; caller frees *ret_fnames[i] and *ret_fnames.
 */
static int
parse_string_array(ESL_JSON *pi, ESL_BUFFER *bf, int arr_idx, char ***ret_fnames)
{
  int    n, c, i;
  int    status;
  char **fnames;

  if (pi->tok[arr_idx].type != eslJSON_ARRAY) { *ret_fnames = NULL; return 0; }
  n = pi->tok[arr_idx].nchild;
  if (n == 0) { *ret_fnames = NULL; return 0; }

  ESL_ALLOC(fnames, sizeof(char *) * n);
  i = 0;
  for (c = pi->tok[arr_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    {
      esl_pos_t slen = esl_json_GetLen(pi, c, bf);
      char     *smem = esl_json_GetMem(pi, c, bf);
      ESL_ALLOC(fnames[i], slen + 1);
      memcpy(fnames[i], smem, slen);
      fnames[i][slen] = '\0';
      i++;
    }
  *ret_fnames = fnames;
  return n;

 ERROR:
  *ret_fnames = NULL;
  return 0;
}


/* =========================================================================
 * parse_ridge_from_obj()
 *   Populate <r> from a JSON OBJECT node at <obj_idx> that contains keys:
 *     feature_mean, feature_std, coef_z, target_mean, loo_mse, [alpha, n_train]
 *   The features list is passed in separately as <fnames> / <nfeat>
 *   (v4.1: features are in the top-level schema; v4.2: features is inline).
 *   Returns eslOK on success.
 */
static int
parse_ridge_from_obj(ESL_JSON *pi, ESL_BUFFER *bf, int obj_idx,
                     char **fnames, int nfeat, FastCalRidge *r)
{
  int     val_idx;
  int     n;
  int     status;
  double *arr = NULL;
  int     i;

  /* feature_mean */
  val_idx = json_find_key(pi, bf, obj_idx, "feature_mean");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n == 0 || arr == NULL) return eslFAIL;
  if (nfeat > 0 && n != nfeat) { free(arr); return eslFAIL; }
  if (nfeat == 0) nfeat = n;
  r->mean  = arr;
  r->nfeat = nfeat;

  /* feature_std */
  val_idx = json_find_key(pi, bf, obj_idx, "feature_std");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n != nfeat || arr == NULL) { free(arr); return eslFAIL; }
  r->std = arr;

  /* coef_z */
  val_idx = json_find_key(pi, bf, obj_idx, "coef_z");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n != nfeat || arr == NULL) { free(arr); return eslFAIL; }
  r->coef = arr;

  /* target_mean (intercept) */
  val_idx = json_find_key(pi, bf, obj_idx, "target_mean");
  if (val_idx < 0) return eslFAIL;
  r->intercept = json_tok_to_double(pi, val_idx, bf);

  /* loo_mse */
  val_idx = json_find_key(pi, bf, obj_idx, "loo_mse");
  if (val_idx < 0) return eslFAIL;
  r->loo_mse = json_tok_to_double(pi, val_idx, bf);

  /* Populate fnames (copy from schema-level list or inline list) */
  ESL_ALLOC(r->fnames, sizeof(char *) * nfeat);
  for (i = 0; i < nfeat; i++)
    {
      r->fnames[i] = strdup(fnames[i]);
      if (r->fnames[i] == NULL) return eslEMEM;
    }

  return eslOK;

 ERROR:
  return eslEMEM;
}


/* =========================================================================
 * v4.1 JSON schema parser (STR lambda and STR mu)
 *
 * v4.1 layout:
 *   { "schema": { "STR_features": [...], "NOSS_features": [...] },
 *     "modes": {
 *       "ECMLC": {
 *         "STR": { "tiny": {ridge}, "small": {ridge}, "medlarge": {ridge}, ... },
 *         "NOSS": {ridge}               <- for lambda file: single ridge (not bucketed)
 *                                       <- for mu file: { "mu_extrap": {ridge}, "mu_orig": {ridge} }
 *       }, ...
 *     }
 *   }
 *
 * For lambda file (is_mu=0): parse modes[mode]["STR"][bucket] → str_lambda[bk][mode]
 * For mu file    (is_mu=1): parse modes[mode]["STR"][bucket]["mu_extrap"] and ["mu_orig"]
 *
 * Note: v4.1 NOSS ridges are superseded by v4.2 NOSS; we skip them.
 */
static int
parse_v41(ESL_JSON *pi, ESL_BUFFER *bf, int is_mu,
          FastCalRidge str_lambda[][N_MODES],
          FastCalRidge str_mu_extrap[][N_MODES],
          FastCalRidge str_mu_orig[][N_MODES])
{
  static const char *mode_names[N_MODES] = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const char *bucket_names[] = {"tiny","small","medlarge","medlarge_local",NULL};
  static const int   bucket_idx[]   = { 0,     1,      2,         2               };

  int status;
  int root_idx  = 0;  /* root is always tok[0], an OBJECT */
  int schema_idx, str_feat_arr, modes_idx;
  int mode_idx;
  int m, bi;

  /* Parse schema.STR_features → get the global feature list */
  schema_idx = json_find_key(pi, bf, root_idx, "schema");
  if (schema_idx < 0) return eslFAIL;
  str_feat_arr = json_find_key(pi, bf, schema_idx, "STR_features");
  if (str_feat_arr < 0) return eslFAIL;

  /* Collect global STR feature names */
  char **str_fnames = NULL;
  int    str_nfeat  = parse_string_array(pi, bf, str_feat_arr, &str_fnames);
  if (str_nfeat == 0) return eslFAIL;

  /* Get modes object */
  modes_idx = json_find_key(pi, bf, root_idx, "modes");
  if (modes_idx < 0) { status = eslFAIL; goto CLEANUP; }

  for (m = 0; m < N_MODES; m++)
    {
      int mode_obj = json_find_key(pi, bf, modes_idx, mode_names[m]);
      if (mode_obj < 0) continue;   /* mode not in this file */

      int str_obj = json_find_key(pi, bf, mode_obj, "STR");
      if (str_obj < 0) continue;

      /* Iterate over buckets */
      for (bi = 0; bucket_names[bi] != NULL; bi++)
        {
          int bk   = bucket_idx[bi];
          int bk_obj = json_find_key(pi, bf, str_obj, bucket_names[bi]);
          if (bk_obj < 0) continue;  /* bucket not present for this mode */

          if (!is_mu)
            {
              /* Lambda file: bk_obj IS the ridge object */
              if (str_lambda[bk][m].nfeat > 0) continue; /* already filled by earlier alias */
              status = parse_ridge_from_obj(pi, bf, bk_obj, str_fnames, str_nfeat, &str_lambda[bk][m]);
              if (status != eslOK) goto CLEANUP;
            }
          else
            {
              /* Mu file: bk_obj has sub-keys "mu_extrap" and "mu_orig" */
              int me_obj = json_find_key(pi, bf, bk_obj, "mu_extrap");
              int mo_obj = json_find_key(pi, bf, bk_obj, "mu_orig");

              if (me_obj >= 0 && str_mu_extrap[bk][m].nfeat == 0)
                {
                  status = parse_ridge_from_obj(pi, bf, me_obj, str_fnames, str_nfeat, &str_mu_extrap[bk][m]);
                  if (status != eslOK) goto CLEANUP;
                }
              if (mo_obj >= 0 && str_mu_orig[bk][m].nfeat == 0)
                {
                  status = parse_ridge_from_obj(pi, bf, mo_obj, str_fnames, str_nfeat, &str_mu_orig[bk][m]);
                  if (status != eslOK) goto CLEANUP;
                }
            }
        }
    }
  status = eslOK;

 CLEANUP:
  if (str_fnames) {
    int i;
    for (i = 0; i < str_nfeat; i++) free(str_fnames[i]);
    free(str_fnames);
  }
  return status;
}


/* =========================================================================
 * v4.2 JSON schema parser (STR large/huge and NOSS tiny/small/medlarge)
 *
 * v4.2 layout (lambda file):
 *   { "design": ..., "modes": [...], "buckets": [...],
 *     "lambda": { "large": { "ECMLC": {ridge}, ... }, "huge": {...} } }
 *
 * v4.2 layout (mu file):
 *   { "design": ..., "modes": [...], "buckets": [...],
 *     "mu_extrap": { "large": { "ECMLC": {ridge}, ... }, ... },
 *     "mu_orig":   { ... } }
 *
 * Ridge object has INLINE "features" list (unlike v4.1).
 * target can be "lambda", "mu_extrap", "mu_orig".
 *
 * Populates whichever of the *_lambda/*_mu_extrap/*_mu_orig arrays we pass.
 * STR arrays: pass str_*; NOSS arrays: pass noss_*.
 * Unused target arrays: pass NULL.
 */
static int
parse_v42_target(ESL_JSON *pi, ESL_BUFFER *bf,
                 const char *target_key,   /* "lambda", "mu_extrap", or "mu_orig" */
                 FastCalRidge dest[][N_MODES])
{
  static const char *mode_names[N_MODES] = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const struct { const char *name; int idx; } bucket_map[] = {
    {"tiny",     BUCKET_TINY     },
    {"small",    BUCKET_SMALL    },
    {"medlarge", BUCKET_MEDLARGE },
    {"large",    BUCKET_LARGE    },
    {"huge",     BUCKET_HUGE     },
    {NULL, 0}
  };

  int status;
  int root_idx = 0;
  int target_obj;
  int bi, m;

  target_obj = json_find_key(pi, bf, root_idx, target_key);
  if (target_obj < 0) return eslOK;  /* key absent → nothing to do */
  if (pi->tok[target_obj].type != eslJSON_OBJECT) return eslFAIL;

  for (bi = 0; bucket_map[bi].name != NULL; bi++)
    {
      int bk     = bucket_map[bi].idx;
      int bk_obj = json_find_key(pi, bf, target_obj, bucket_map[bi].name);
      if (bk_obj < 0) continue;

      for (m = 0; m < N_MODES; m++)
        {
          int ridge_obj = json_find_key(pi, bf, bk_obj, mode_names[m]);
          if (ridge_obj < 0) continue;
          if (dest[bk][m].nfeat > 0) continue;  /* already set */

          /* Inline features array */
          int feat_arr = json_find_key(pi, bf, ridge_obj, "features");
          if (feat_arr < 0) return eslFAIL;

          char **fnames = NULL;
          int    nfeat  = parse_string_array(pi, bf, feat_arr, &fnames);
          if (nfeat == 0) return eslFAIL;

          status = parse_ridge_from_obj(pi, bf, ridge_obj, fnames, nfeat, &dest[bk][m]);

          /* Free fnames (ridge owns its own copies) */
          { int i; for (i = 0; i < nfeat; i++) free(fnames[i]); free(fnames); }

          if (status != eslOK) return status;
        }
    }
  return eslOK;
}


static int
parse_v42(ESL_JSON *pi, ESL_BUFFER *bf,
          FastCalRidge dest_lambda[][N_MODES],
          FastCalRidge dest_mu_extrap[][N_MODES],
          FastCalRidge dest_mu_orig[][N_MODES])
{
  int status;

  if (dest_lambda    && (status = parse_v42_target(pi, bf, "lambda",    dest_lambda))    != eslOK) return status;
  if (dest_mu_extrap && (status = parse_v42_target(pi, bf, "mu_extrap", dest_mu_extrap)) != eslOK) return status;
  if (dest_mu_orig   && (status = parse_v42_target(pi, bf, "mu_orig",   dest_mu_orig))   != eslOK) return status;
  return eslOK;
}


/* =========================================================================
 * load_models()
 *   Parse all 6 embedded JSONs into g_models on first call.
 *   Idempotent (returns eslOK immediately if already loaded).
 */
static int
load_models(void)
{
  int status;

  if (g_models.loaded) return eslOK;

  /* 1. v4.1 STR lambda (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v41_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v41_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v41(pi, bf, /*is_mu=*/0,
                       g_models.str_lambda, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 2. v4.1 STR mu (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v41_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v41_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v41(pi, bf, /*is_mu=*/1,
                       g_models.str_lambda, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 3. v4.2 STR lambda (large/huge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v42_largehuge_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v42_largehuge_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, g_models.str_lambda, NULL, NULL);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 4. v4.2 STR mu (large/huge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v42_largehuge_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v42_largehuge_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, NULL, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 5. v4.2 NOSS lambda (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v42_noss_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v42_noss_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, g_models.noss_lambda, NULL, NULL);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 6. v4.2 NOSS mu (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v42_noss_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v42_noss_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, NULL, g_models.noss_mu_extrap, g_models.noss_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* Record the embedded version hash */
  strncpy(g_models.models_version, fast_cal_models_version, 64);
  g_models.models_version[64] = '\0';
  g_models.loaded = 1;
  return eslOK;
}


/* =========================================================================
 * Public API
 */

/* cm_FastCalibrate()
 * Phase 1 stub: returns eslFAIL with no side effects.
 * Real implementation in Phase 4.
 */
int
cm_FastCalibrate(CM_t *cm)
{
  (void)cm;  /* suppress unused-parameter warning */
  return eslFAIL;
}


/* cm_FastCalibrateCleanup()
 * Free all model memory. Idempotent.
 */
void
cm_FastCalibrateCleanup(void)
{
  int b, m;
  if (!g_models.loaded) return;
  for (b = 0; b < N_BUCKETS; b++)
    for (m = 0; m < N_MODES; m++)
      {
        ridge_free(&g_models.str_lambda    [b][m]);
        ridge_free(&g_models.str_mu_extrap [b][m]);
        ridge_free(&g_models.str_mu_orig   [b][m]);
        ridge_free(&g_models.noss_lambda   [b][m]);
        ridge_free(&g_models.noss_mu_extrap[b][m]);
        ridge_free(&g_models.noss_mu_orig  [b][m]);
      }
  g_models.loaded = 0;
}


/* cm_FastCalibrate_PrintModels()
 * Dump all loaded ridges to <fp> in a format suitable for diffing against
 * the source JSONs. Triggers lazy load on first call.
 * Returns eslOK on success, eslFAIL on load error.
 */
int
cm_FastCalibrate_PrintModels(FILE *fp)
{
  static const char *bucket_names[N_BUCKETS] = {"tiny","small","medlarge","large","huge"};
  static const char *mode_names  [N_MODES]   = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const char *target_labels[6] = {
    "STR_lambda", "STR_mu_extrap", "STR_mu_orig",
    "NOSS_lambda","NOSS_mu_extrap","NOSS_mu_orig"
  };
  FastCalRidge (*tables[6])[N_MODES] = {
    g_models.str_lambda,    g_models.str_mu_extrap, g_models.str_mu_orig,
    g_models.noss_lambda,   g_models.noss_mu_extrap,g_models.noss_mu_orig
  };

  int status;
  int t, b, m, i;

  if ((status = load_models()) != eslOK) return status;

  fprintf(fp, "# cm_fast_calibrate models dump\n");
  fprintf(fp, "# models_version: %s\n", g_models.models_version);

  for (t = 0; t < 6; t++)
    for (b = 0; b < N_BUCKETS; b++)
      for (m = 0; m < N_MODES; m++)
        {
          FastCalRidge *r = &tables[t][b][m];
          if (r->nfeat == 0) continue;  /* empty slot */

          fprintf(fp, "\n[%s][%s][%s]\n", target_labels[t], bucket_names[b], mode_names[m]);
          fprintf(fp, "  nfeat:      %d\n", r->nfeat);
          fprintf(fp, "  intercept:  %.10f\n", r->intercept);
          fprintf(fp, "  loo_mse:    %.10f\n", r->loo_mse);
          for (i = 0; i < r->nfeat; i++)
            fprintf(fp, "  feat[%2d]  %-30s  mean=%.10f  std=%.10f  coef=%.10f\n",
                    i, r->fnames[i], r->mean[i], r->std[i], r->coef[i]);
        }

  return eslOK;
}
