/* cm_fast_calibrate.c
 * Fast CM calibration via ridge regression on compiled-in JSON models.
 *
 * Phase 1: JSON parsing, model loading, and print_models() debug helper.
 * Phase 2: feature extraction (cm_FastCalibrate_ExtractFeatures), 20 features.
 * Phase 3: topo_fraglen_v2 (noend basic) + C1_OLD legacy, 7 more features.
 * cm_FastCalibrate() is a stub returning eslFAIL (real prediction: Phase 4).
 *
 * JSON layout (two schemas):
 *   v4.1 (STR tiny/small/medlarge):
 *     modes[mode]["STR"][bucket]   → ridge {alpha, loo_mse, coef_z, feature_mean, feature_std, target_mean, n_train}
 *                                    features list is at top-level schema["STR_features"]
 *   v4.2 (STR large/huge, NOSS tiny/small/medlarge):
 *     lambda[bucket][mode]         → ridge {features, feature_mean, feature_std, coef_z, target_mean, alpha, loo_mse}
 *     mu_extrap[bucket][mode]      → ridge (same)
 *     mu_orig[bucket][mode]        → ridge (same)
 *
 * Model mapping:
 *   production_models_v41.json        → g_models.str_lambda    [0..2][*]   (buckets tiny/small/medlarge)
 *   production_mu_models_v41.json     → g_models.str_mu_extrap [0..2][*]
 *                                     → g_models.str_mu_orig   [0..2][*]
 *   production_models_v42_largehuge   → g_models.str_lambda    [3..4][*]   (buckets large/huge)
 *   production_mu_models_v42_largehuge→ g_models.str_mu_extrap [3..4][*]
 *                                     → g_models.str_mu_orig   [3..4][*]
 *   production_models_v42_noss        → g_models.noss_lambda   [0..2][*]
 *   production_mu_models_v42_noss     → g_models.noss_mu_extrap[0..2][*]
 *                                     → g_models.noss_mu_orig  [0..2][*]
 *
 * See: CPORT_SPEC.md §3-5.
 */

#include "esl_config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "easel.h"
#include "esl_buffer.h"
#include "esl_json.h"

#include "infernal.h"
#include "cm_fast_calibrate.h"

/* Embedded JSON data arrays (generated by embed_fastcal_models.sh via xxd -i) */
#include "cm_fast_calibrate_models.h"

/* =========================================================================
 * Internal constants
 */

#define N_BUCKETS  5   /* tiny=0, small=1, medlarge=2, large=3, huge=4    */
#define N_MODES    4   /* ECMLC=0, ECMLI=1, ECMGC=2, ECMGI=3             */

/* Bucket indices */
#define BUCKET_TINY      0
#define BUCKET_SMALL     1
#define BUCKET_MEDLARGE  2
#define BUCKET_LARGE     3
#define BUCKET_HUGE      4

/* Mode indices */
#define MODE_ECMLC  0
#define MODE_ECMLI  1
#define MODE_ECMGC  2
#define MODE_ECMGI  3

/* =========================================================================
 * Data structures
 */

typedef struct {
  int      nfeat;      /* number of features; 0 = slot unused                */
  char   **fnames;     /* feature name strings [nfeat], NULL-terminated list  */
  double  *mean;       /* feature_mean[nfeat]                                  */
  double  *std;        /* feature_std[nfeat]                                   */
  double  *coef;       /* coef_z[nfeat]                                        */
  double   intercept;  /* target_mean                                          */
  double   loo_mse;    /* informational only                                   */
} FastCalRidge;

typedef struct {
  FastCalRidge str_lambda    [N_BUCKETS][N_MODES];
  FastCalRidge str_mu_extrap [N_BUCKETS][N_MODES];
  FastCalRidge str_mu_orig   [N_BUCKETS][N_MODES];
  FastCalRidge noss_lambda   [N_BUCKETS][N_MODES];
  FastCalRidge noss_mu_extrap[N_BUCKETS][N_MODES];
  FastCalRidge noss_mu_orig  [N_BUCKETS][N_MODES];
  char         models_version[65];   /* SHA-256 hex of concatenated JSONs + NUL */
  int          loaded;
} FastCalModelSet;

static FastCalModelSet g_models;   /* zero-initialised by C spec */


/* =========================================================================
 * Internal helper: free a single ridge
 */
static void
ridge_free(FastCalRidge *r)
{
  if (r == NULL || r->nfeat == 0) return;
  if (r->fnames) {
    int i;
    for (i = 0; i < r->nfeat; i++) free(r->fnames[i]);
    free(r->fnames);
    r->fnames = NULL;
  }
  if (r->mean) { free(r->mean); r->mean = NULL; }
  if (r->std)  { free(r->std);  r->std  = NULL; }
  if (r->coef) { free(r->coef); r->coef = NULL; }
  r->nfeat = 0;
}


/* =========================================================================
 * Internal helper: parse a double from a JSON number token
 *   esl_json_ReadFloat only returns float; we need double precision.
 */
static double
json_tok_to_double(ESL_JSON *pi, int idx, ESL_BUFFER *bf)
{
  char     *p   = esl_json_GetMem(pi, idx, bf);
  esl_pos_t n   = esl_json_GetLen(pi, idx, bf);
  char      buf[64];
  if (n >= 63) n = 62;
  memcpy(buf, p, (size_t)n);
  buf[n] = '\0';
  return strtod(buf, NULL);
}


/* =========================================================================
 * Internal helper: check if a KEY token matches a string
 */
static int
key_matches(ESL_JSON *pi, int idx, ESL_BUFFER *bf, const char *want)
{
  char     *p  = esl_json_GetMem(pi, idx, bf);
  esl_pos_t n  = esl_json_GetLen(pi, idx, bf);
  size_t    wn = strlen(want);
  if ((size_t)n != wn) return 0;
  return (memcmp(p, want, wn) == 0);
}


/* =========================================================================
 * Internal helper: find the first child of an object/array with a KEY
 * that matches <keyname>. Returns the index of the VALUE (not the key).
 * Returns -1 if not found.
 */
static int
json_find_key(ESL_JSON *pi, ESL_BUFFER *bf, int obj_idx, const char *keyname)
{
  int c;
  if (pi->tok[obj_idx].type != eslJSON_OBJECT) return -1;
  for (c = pi->tok[obj_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    {
      /* In esl_json, obj children are alternating key/value.
       * Each "child" is a key; its value is key->nextsib. */
      if (pi->tok[c].type == eslJSON_KEY && key_matches(pi, c, bf, keyname))
        return pi->tok[c].nextsib;   /* value follows the key in the sibling list */
    }
  return -1;
}


/* =========================================================================
 * Internal helper: parse a double[] array from a JSON ARRAY token.
 * Allocates *ret_arr (caller frees). Returns number of elements.
 */
static int
parse_double_array(ESL_JSON *pi, ESL_BUFFER *bf, int arr_idx, double **ret_arr)
{
  int     n, c, i;
  int     status;
  double *arr;

  if (pi->tok[arr_idx].type != eslJSON_ARRAY) { *ret_arr = NULL; return 0; }
  n = pi->tok[arr_idx].nchild;
  if (n == 0) { *ret_arr = NULL; return 0; }

  ESL_ALLOC(arr, sizeof(double) * n);
  i = 0;
  for (c = pi->tok[arr_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    arr[i++] = json_tok_to_double(pi, c, bf);

  *ret_arr = arr;
  return n;

 ERROR:
  *ret_arr = NULL;
  return 0;
}


/* =========================================================================
 * Internal helper: parse a string[] array from a JSON ARRAY token.
 * Returns nfeat; caller frees *ret_fnames[i] and *ret_fnames.
 */
static int
parse_string_array(ESL_JSON *pi, ESL_BUFFER *bf, int arr_idx, char ***ret_fnames)
{
  int    n, c, i;
  int    status;
  char **fnames;

  if (pi->tok[arr_idx].type != eslJSON_ARRAY) { *ret_fnames = NULL; return 0; }
  n = pi->tok[arr_idx].nchild;
  if (n == 0) { *ret_fnames = NULL; return 0; }

  ESL_ALLOC(fnames, sizeof(char *) * n);
  i = 0;
  for (c = pi->tok[arr_idx].firstchild; c != -1; c = pi->tok[c].nextsib)
    {
      esl_pos_t slen = esl_json_GetLen(pi, c, bf);
      char     *smem = esl_json_GetMem(pi, c, bf);
      ESL_ALLOC(fnames[i], slen + 1);
      memcpy(fnames[i], smem, slen);
      fnames[i][slen] = '\0';
      i++;
    }
  *ret_fnames = fnames;
  return n;

 ERROR:
  *ret_fnames = NULL;
  return 0;
}


/* =========================================================================
 * parse_ridge_from_obj()
 *   Populate <r> from a JSON OBJECT node at <obj_idx> that contains keys:
 *     feature_mean, feature_std, coef_z, target_mean, loo_mse, [alpha, n_train]
 *   The features list is passed in separately as <fnames> / <nfeat>
 *   (v4.1: features are in the top-level schema; v4.2: features is inline).
 *   Returns eslOK on success.
 */
static int
parse_ridge_from_obj(ESL_JSON *pi, ESL_BUFFER *bf, int obj_idx,
                     char **fnames, int nfeat, FastCalRidge *r)
{
  int     val_idx;
  int     n;
  int     status;
  double *arr = NULL;
  int     i;

  /* feature_mean */
  val_idx = json_find_key(pi, bf, obj_idx, "feature_mean");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n == 0 || arr == NULL) return eslFAIL;
  if (nfeat > 0 && n != nfeat) { free(arr); return eslFAIL; }
  if (nfeat == 0) nfeat = n;
  r->mean  = arr;
  r->nfeat = nfeat;

  /* feature_std */
  val_idx = json_find_key(pi, bf, obj_idx, "feature_std");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n != nfeat || arr == NULL) { free(arr); return eslFAIL; }
  r->std = arr;

  /* coef_z */
  val_idx = json_find_key(pi, bf, obj_idx, "coef_z");
  if (val_idx < 0) return eslFAIL;
  n = parse_double_array(pi, bf, val_idx, &arr);
  if (n != nfeat || arr == NULL) { free(arr); return eslFAIL; }
  r->coef = arr;

  /* target_mean (intercept) */
  val_idx = json_find_key(pi, bf, obj_idx, "target_mean");
  if (val_idx < 0) return eslFAIL;
  r->intercept = json_tok_to_double(pi, val_idx, bf);

  /* loo_mse */
  val_idx = json_find_key(pi, bf, obj_idx, "loo_mse");
  if (val_idx < 0) return eslFAIL;
  r->loo_mse = json_tok_to_double(pi, val_idx, bf);

  /* Populate fnames (copy from schema-level list or inline list) */
  ESL_ALLOC(r->fnames, sizeof(char *) * nfeat);
  for (i = 0; i < nfeat; i++)
    {
      r->fnames[i] = strdup(fnames[i]);
      if (r->fnames[i] == NULL) return eslEMEM;
    }

  return eslOK;

 ERROR:
  return eslEMEM;
}


/* =========================================================================
 * v4.1 JSON schema parser (STR lambda and STR mu)
 *
 * v4.1 layout:
 *   { "schema": { "STR_features": [...], "NOSS_features": [...] },
 *     "modes": {
 *       "ECMLC": {
 *         "STR": { "tiny": {ridge}, "small": {ridge}, "medlarge": {ridge}, ... },
 *         "NOSS": {ridge}               <- for lambda file: single ridge (not bucketed)
 *                                       <- for mu file: { "mu_extrap": {ridge}, "mu_orig": {ridge} }
 *       }, ...
 *     }
 *   }
 *
 * For lambda file (is_mu=0): parse modes[mode]["STR"][bucket] → str_lambda[bk][mode]
 * For mu file    (is_mu=1): parse modes[mode]["STR"][bucket]["mu_extrap"] and ["mu_orig"]
 *
 * Note: v4.1 NOSS ridges are superseded by v4.2 NOSS; we skip them.
 */
static int
parse_v41(ESL_JSON *pi, ESL_BUFFER *bf, int is_mu,
          FastCalRidge str_lambda[][N_MODES],
          FastCalRidge str_mu_extrap[][N_MODES],
          FastCalRidge str_mu_orig[][N_MODES])
{
  static const char *mode_names[N_MODES] = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const char *bucket_names[] = {"tiny","small","medlarge","medlarge_local",NULL};
  static const int   bucket_idx[]   = { 0,     1,      2,         2               };

  int status;
  int root_idx  = 0;  /* root is always tok[0], an OBJECT */
  int schema_idx, str_feat_arr, modes_idx;
  int mode_idx;
  int m, bi;

  /* Parse schema.STR_features → get the global feature list */
  schema_idx = json_find_key(pi, bf, root_idx, "schema");
  if (schema_idx < 0) return eslFAIL;
  str_feat_arr = json_find_key(pi, bf, schema_idx, "STR_features");
  if (str_feat_arr < 0) return eslFAIL;

  /* Collect global STR feature names */
  char **str_fnames = NULL;
  int    str_nfeat  = parse_string_array(pi, bf, str_feat_arr, &str_fnames);
  if (str_nfeat == 0) return eslFAIL;

  /* Get modes object */
  modes_idx = json_find_key(pi, bf, root_idx, "modes");
  if (modes_idx < 0) { status = eslFAIL; goto CLEANUP; }

  for (m = 0; m < N_MODES; m++)
    {
      int mode_obj = json_find_key(pi, bf, modes_idx, mode_names[m]);
      if (mode_obj < 0) continue;   /* mode not in this file */

      int str_obj = json_find_key(pi, bf, mode_obj, "STR");
      if (str_obj < 0) continue;

      /* Iterate over buckets */
      for (bi = 0; bucket_names[bi] != NULL; bi++)
        {
          int bk   = bucket_idx[bi];
          int bk_obj = json_find_key(pi, bf, str_obj, bucket_names[bi]);
          if (bk_obj < 0) continue;  /* bucket not present for this mode */

          if (!is_mu)
            {
              /* Lambda file: bk_obj IS the ridge object */
              if (str_lambda[bk][m].nfeat > 0) continue; /* already filled by earlier alias */
              status = parse_ridge_from_obj(pi, bf, bk_obj, str_fnames, str_nfeat, &str_lambda[bk][m]);
              if (status != eslOK) goto CLEANUP;
            }
          else
            {
              /* Mu file: bk_obj has sub-keys "mu_extrap" and "mu_orig" */
              int me_obj = json_find_key(pi, bf, bk_obj, "mu_extrap");
              int mo_obj = json_find_key(pi, bf, bk_obj, "mu_orig");

              if (me_obj >= 0 && str_mu_extrap[bk][m].nfeat == 0)
                {
                  status = parse_ridge_from_obj(pi, bf, me_obj, str_fnames, str_nfeat, &str_mu_extrap[bk][m]);
                  if (status != eslOK) goto CLEANUP;
                }
              if (mo_obj >= 0 && str_mu_orig[bk][m].nfeat == 0)
                {
                  status = parse_ridge_from_obj(pi, bf, mo_obj, str_fnames, str_nfeat, &str_mu_orig[bk][m]);
                  if (status != eslOK) goto CLEANUP;
                }
            }
        }
    }
  status = eslOK;

 CLEANUP:
  if (str_fnames) {
    int i;
    for (i = 0; i < str_nfeat; i++) free(str_fnames[i]);
    free(str_fnames);
  }
  return status;
}


/* =========================================================================
 * v4.2 JSON schema parser (STR large/huge and NOSS tiny/small/medlarge)
 *
 * v4.2 layout (lambda file):
 *   { "design": ..., "modes": [...], "buckets": [...],
 *     "lambda": { "large": { "ECMLC": {ridge}, ... }, "huge": {...} } }
 *
 * v4.2 layout (mu file):
 *   { "design": ..., "modes": [...], "buckets": [...],
 *     "mu_extrap": { "large": { "ECMLC": {ridge}, ... }, ... },
 *     "mu_orig":   { ... } }
 *
 * Ridge object has INLINE "features" list (unlike v4.1).
 * target can be "lambda", "mu_extrap", "mu_orig".
 *
 * Populates whichever of the *_lambda/*_mu_extrap/*_mu_orig arrays we pass.
 * STR arrays: pass str_*; NOSS arrays: pass noss_*.
 * Unused target arrays: pass NULL.
 */
static int
parse_v42_target(ESL_JSON *pi, ESL_BUFFER *bf,
                 const char *target_key,   /* "lambda", "mu_extrap", or "mu_orig" */
                 FastCalRidge dest[][N_MODES])
{
  static const char *mode_names[N_MODES] = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const struct { const char *name; int idx; } bucket_map[] = {
    {"tiny",     BUCKET_TINY     },
    {"small",    BUCKET_SMALL    },
    {"medlarge", BUCKET_MEDLARGE },
    {"large",    BUCKET_LARGE    },
    {"huge",     BUCKET_HUGE     },
    {NULL, 0}
  };

  int status;
  int root_idx = 0;
  int target_obj;
  int bi, m;

  target_obj = json_find_key(pi, bf, root_idx, target_key);
  if (target_obj < 0) return eslOK;  /* key absent → nothing to do */
  if (pi->tok[target_obj].type != eslJSON_OBJECT) return eslFAIL;

  for (bi = 0; bucket_map[bi].name != NULL; bi++)
    {
      int bk     = bucket_map[bi].idx;
      int bk_obj = json_find_key(pi, bf, target_obj, bucket_map[bi].name);
      if (bk_obj < 0) continue;

      for (m = 0; m < N_MODES; m++)
        {
          int ridge_obj = json_find_key(pi, bf, bk_obj, mode_names[m]);
          if (ridge_obj < 0) continue;
          if (dest[bk][m].nfeat > 0) continue;  /* already set */

          /* Inline features array */
          int feat_arr = json_find_key(pi, bf, ridge_obj, "features");
          if (feat_arr < 0) return eslFAIL;

          char **fnames = NULL;
          int    nfeat  = parse_string_array(pi, bf, feat_arr, &fnames);
          if (nfeat == 0) return eslFAIL;

          status = parse_ridge_from_obj(pi, bf, ridge_obj, fnames, nfeat, &dest[bk][m]);

          /* Free fnames (ridge owns its own copies) */
          { int i; for (i = 0; i < nfeat; i++) free(fnames[i]); free(fnames); }

          if (status != eslOK) return status;
        }
    }
  return eslOK;
}


static int
parse_v42(ESL_JSON *pi, ESL_BUFFER *bf,
          FastCalRidge dest_lambda[][N_MODES],
          FastCalRidge dest_mu_extrap[][N_MODES],
          FastCalRidge dest_mu_orig[][N_MODES])
{
  int status;

  if (dest_lambda    && (status = parse_v42_target(pi, bf, "lambda",    dest_lambda))    != eslOK) return status;
  if (dest_mu_extrap && (status = parse_v42_target(pi, bf, "mu_extrap", dest_mu_extrap)) != eslOK) return status;
  if (dest_mu_orig   && (status = parse_v42_target(pi, bf, "mu_orig",   dest_mu_orig))   != eslOK) return status;
  return eslOK;
}


/* =========================================================================
 * load_models()
 *   Parse all 6 embedded JSONs into g_models on first call.
 *   Idempotent (returns eslOK immediately if already loaded).
 */
static int
load_models(void)
{
  int status;

  if (g_models.loaded) return eslOK;

  /* 1. v4.1 STR lambda (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v41_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v41_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v41(pi, bf, /*is_mu=*/0,
                       g_models.str_lambda, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 2. v4.1 STR mu (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v41_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v41_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v41(pi, bf, /*is_mu=*/1,
                       g_models.str_lambda, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 3. v4.2 STR lambda (large/huge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v42_largehuge_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v42_largehuge_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, g_models.str_lambda, NULL, NULL);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 4. v4.2 STR mu (large/huge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v42_largehuge_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v42_largehuge_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, NULL, g_models.str_mu_extrap, g_models.str_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 5. v4.2 NOSS lambda (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_models_v42_noss_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_models_v42_noss_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, g_models.noss_lambda, NULL, NULL);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* 6. v4.2 NOSS mu (tiny/small/medlarge) */
  {
    ESL_BUFFER *bf = NULL;
    ESL_JSON   *pi = NULL;
    if ((status = esl_buffer_OpenMem(
           (const char *)__cm_fast_calibrate_data_production_mu_models_v42_noss_json,
           (esl_pos_t)  __cm_fast_calibrate_data_production_mu_models_v42_noss_json_len,
           &bf)) != eslOK) return status;
    if ((status = esl_json_Parse(bf, &pi)) != eslOK)
      { esl_buffer_Close(bf); return status; }
    status = parse_v42(pi, bf, NULL, g_models.noss_mu_extrap, g_models.noss_mu_orig);
    esl_json_Destroy(pi);
    esl_buffer_Close(bf);
    if (status != eslOK) return status;
  }

  /* Record the embedded version hash */
  strncpy(g_models.models_version, fast_cal_models_version, 64);
  g_models.models_version[64] = '\0';
  g_models.loaded = 1;
  return eslOK;
}


/* =========================================================================
 * Public API
 */

/* bucket_of()
 * Map consensus length to bucket index, matching Python bucket_of().
 */
static int
bucket_of(int clen)
{
  if (clen <=  100) return BUCKET_TINY;
  if (clen <=  300) return BUCKET_SMALL;
  if (clen <   700) return BUCKET_MEDLARGE;
  if (clen <  1500) return BUCKET_LARGE;
  return BUCKET_HUGE;
}


/* ridge_predict()
 * Compute the ridge regression prediction for one target.
 * Returns the predicted value, or 0.0 if ridge is empty (nfeat == 0).
 *
 * Formula: pred = intercept + sum_i coef[i] * (feats[idx_i] - mean[i]) / std[i]
 */
static double
ridge_predict(const FastCalRidge *r, const double *feats_full)
{
  double sum = r->intercept;
  int    i;
  for (i = 0; i < r->nfeat; i++)
    {
      int    idx  = cm_FastCalibrate_FeatureIndex(r->fnames[i]);
      double z;
      if (idx < 0) continue;  /* unknown feature name — skip */
      z    = (feats_full[idx] - r->mean[i]) / r->std[i];
      sum += z * r->coef[i];
    }
  return sum;
}


/* cm_FastCalibrate()
 * Predict ECM parameters (λ, μ_extrap, μ_orig) for all 4 ECM modes and
 * populate cm->expA[0..EXP_NMODES-1] in place.
 *
 * Models are lazy-loaded from compiled-in JSON on first call.
 * Returns eslOK on success, eslFAIL if features can't be extracted or a
 * required ridge is empty (nfeat == 0).
 */
int
cm_FastCalibrate(CM_t *cm)
{
  double        feats[FAST_CAL_NFEAT];
  int           bucket;
  int           is_noss;
  int           mode, nd, i;
  int           status;

  /* Lazy model load */
  if (!g_models.loaded)
    {
      if ((status = load_models()) != eslOK) return eslFAIL;
    }

  /* Extract all 27 features */
  if ((status = cm_FastCalibrate_ExtractFeatures(cm, feats)) != eslOK)
    return eslFAIL;

  /* Detect NOSS: no MATP nodes means no base pairs */
  is_noss = 1;
  for (nd = 0; nd < cm->nodes; nd++)
    if (cm->ndtype[nd] == MATP_nd) { is_noss = 0; break; }

  /* Pick bucket, with NOSS huge/large fallback to medlarge */
  bucket = bucket_of(cm->clen);
  if (is_noss && bucket >= BUCKET_LARGE)
    bucket = BUCKET_MEDLARGE;

  /* Allocate cm->expA if needed */
  if (cm->expA == NULL)
    {
      ESL_ALLOC(cm->expA, sizeof(ExpInfo_t *) * EXP_NMODES);
      for (i = 0; i < EXP_NMODES; i++) cm->expA[i] = NULL;
    }
  for (i = 0; i < EXP_NMODES; i++)
    if (cm->expA[i] == NULL)
      {
        cm->expA[i] = CreateExpInfo();
        if (cm->expA[i] == NULL) goto ERROR;
      }

  /* Predict for each ECM mode.
   * Infernal mode indices: EXP_CM_GC=0, EXP_CM_GI=1, EXP_CM_LC=2, EXP_CM_LI=3.
   * Our internal MODE_ECMLC/GC/LI/GI indices map to those via the enum.
   * We iterate over all 4 modes by Infernal's mode indices.
   *
   * Mode name order in models: ECMLC=0, ECMLI=1, ECMGC=2, ECMGI=3 (from JSON parse).
   * Infernal's: EXP_CM_GC=0, EXP_CM_GI=1, EXP_CM_LC=2, EXP_CM_LI=3.
   * Map: Infernal EXP_CM_LC → MODE_ECMLC, EXP_CM_LI → MODE_ECMLI, etc.
   */
  static const int inf_to_model_mode[EXP_NMODES] = {
    MODE_ECMGC,  /* EXP_CM_GC = 0 */
    MODE_ECMGI,  /* EXP_CM_GI = 1 */
    MODE_ECMLC,  /* EXP_CM_LC = 2 */
    MODE_ECMLI,  /* EXP_CM_LI = 3 */
  };

  for (i = 0; i < EXP_NMODES; i++)
    {
      mode = inf_to_model_mode[i];

      FastCalRidge *r_lam, *r_mue, *r_muo;
      if (is_noss) {
        r_lam = &g_models.noss_lambda   [bucket][mode];
        r_mue = &g_models.noss_mu_extrap[bucket][mode];
        r_muo = &g_models.noss_mu_orig  [bucket][mode];
      } else {
        r_lam = &g_models.str_lambda   [bucket][mode];
        r_mue = &g_models.str_mu_extrap[bucket][mode];
        r_muo = &g_models.str_mu_orig  [bucket][mode];
      }

      if (r_lam->nfeat == 0) return eslFAIL;  /* no ridge for this slot */

      double lam = ridge_predict(r_lam, feats);
      double mu_e = (r_mue->nfeat > 0) ? ridge_predict(r_mue, feats) : 0.0;
      double mu_o = (r_muo->nfeat > 0) ? ridge_predict(r_muo, feats) : 0.0;

      /* Conventional calibration metadata */
      SetExpInfo(cm->expA[i], lam, mu_o, 1.6e6, 250, 0.01);
      /* Override mu_extrap with the directly-predicted value
       * (SetExpInfo would recompute it from mu_orig/lambda/tailp). */
      if (r_mue->nfeat > 0)
        cm->expA[i]->mu_extrap = mu_e;
    }

  return eslOK;

 ERROR:
  return eslEMEM;
}


/* cm_FastCalibrateCleanup()
 * Free all model memory. Idempotent.
 */
void
cm_FastCalibrateCleanup(void)
{
  int b, m;
  if (!g_models.loaded) return;
  for (b = 0; b < N_BUCKETS; b++)
    for (m = 0; m < N_MODES; m++)
      {
        ridge_free(&g_models.str_lambda    [b][m]);
        ridge_free(&g_models.str_mu_extrap [b][m]);
        ridge_free(&g_models.str_mu_orig   [b][m]);
        ridge_free(&g_models.noss_lambda   [b][m]);
        ridge_free(&g_models.noss_mu_extrap[b][m]);
        ridge_free(&g_models.noss_mu_orig  [b][m]);
      }
  g_models.loaded = 0;
}


/* =========================================================================
 * Phase 2 Feature Extraction
 */

/* Feature name table — indexed by FAST_CAL_FEAT_* enum.
 * Must stay in sync with the enum in cm_fast_calibrate.h.
 * 27 entries total (Phase 2: 0..19, Phase 3: 20..26).
 */
static const char *fast_cal_feature_names[] = {
    "clen",                  /* 0  */
    "mean_L_noss",           /* 1  */
    "var_L_noss",            /* 2  */
    "KL_noss_to_unif",       /* 3  */
    "p_full_length",         /* 4  */
    "n_matp",                /* 5  */
    "pct_matp",              /* 6  */
    "bp_density",            /* 7  */
    "mean_matp_relent",      /* 8  */
    "max_matp_relent",       /* 9  */
    "sum_matp_relent",       /* 10 */
    "mean_ml_relent",        /* 11 */
    "mean_node_mean_g",      /* 12 */
    "mean_node_var_g",       /* 13 */
    "ES_full_g",             /* 14 */
    "VarS_full_g",           /* 15 */
    "mean_ES_g",             /* 16 */
    "var_ES_g",              /* 17 */
    "mean_VarS_g",           /* 18 */
    "cov_L_ES_g",            /* 19 */
    "noend_mean_L",          /* 20 */
    "noend_var_L",           /* 21 */
    "noend_KL_to_unif",      /* 22 */
    "noend_p_full_length",   /* 23 */
    "mean_L_str",            /* 24 */
    "var_L_str",             /* 25 */
    "KL_str_to_unif",        /* 26 */
    NULL
};

/* cm_FastCalibrate_FeatureName()
 * Return the name string for feature index idx, or NULL if out of range.
 */
const char *
cm_FastCalibrate_FeatureName(int idx)
{
  if (idx < 0 || idx >= FAST_CAL_NFEAT) return NULL;
  return fast_cal_feature_names[idx];
}

/* cm_FastCalibrate_FeatureIndex()
 * Return the index for a feature name, or -1 if not found.
 */
int
cm_FastCalibrate_FeatureIndex(const char *name)
{
  int i;
  if (name == NULL) return -1;
  for (i = 0; i < FAST_CAL_NFEAT; i++)
    if (strcmp(fast_cal_feature_names[i], name) == 0) return i;
  return -1;
}


/* extract_clen()
 * Trivially store clen as a feature.
 */
static int
extract_clen(CM_t *cm, double *feats)
{
  feats[FAST_CAL_FEAT_clen] = (double) cm->clen;
  return eslOK;
}


/* extract_noss_fraglen()
 * Port of Python fraglen_features(clen, pbegin, pend) from fast_cmcalibrate.py.
 *
 * Computes: mean_L_noss, var_L_noss, KL_noss_to_unif, p_full_length.
 *
 * The fragment length distribution model:
 *   - entry probs: p_entry[1] = 1 - pbegin (full-length, no local begin)
 *                  p_entry[i] = pbegin / (N-1) for i in [2, N]
 *   - exit rate:   r = pend / (N-1)
 *   - p_L[L] = sum over all entry points i: p_entry[i] * reach_to_length_L
 *     where reach *= (1 - r) at each step, exit_here = reach * (r if j<N else 1)
 *   - p_full_length = p_entry[1] * (1 - r)^(N-1)
 */
static int
extract_noss_fraglen(CM_t *cm, double *feats)
{
  int    N       = cm->clen;
  double pbegin  = (double) cm->pbegin;
  double pend    = (double) cm->pend;
  double r, total_P, mean_L, var_L, kl, p_full;
  double *p_entry = NULL;
  double *p_L     = NULL;
  int     i, j, L;
  double  reach, exit_here;
  int     status;

  if (N <= 1) {
    feats[FAST_CAL_FEAT_mean_L_noss]      = 0.0;
    feats[FAST_CAL_FEAT_var_L_noss]       = 0.0;
    feats[FAST_CAL_FEAT_KL_noss_to_unif]  = 0.0;
    feats[FAST_CAL_FEAT_p_full_length]    = 0.0;
    return eslOK;
  }

  r = pend / (double)(N - 1);

  ESL_ALLOC(p_entry, sizeof(double) * (N + 1));
  ESL_ALLOC(p_L,     sizeof(double) * (N + 1));

  /* Entry probabilities */
  p_entry[0] = 0.0;
  p_entry[1] = 1.0 - pbegin;
  for (i = 2; i <= N; i++)
    p_entry[i] = pbegin / (double)(N - 1);

  /* Fragment length probabilities */
  for (L = 0; L <= N; L++) p_L[L] = 0.0;

  for (i = 1; i <= N; i++) {
    if (p_entry[i] == 0.0) continue;
    reach = 1.0;
    for (j = i; j <= N; j++) {
      exit_here = reach * ((j < N) ? r : 1.0);
      L = j - i + 1;
      p_L[L] += p_entry[i] * exit_here;
      reach *= (1.0 - r);
    }
  }

  /* Normalize (should already sum to 1.0 but be safe) */
  total_P = 0.0;
  for (L = 1; L <= N; L++) total_P += p_L[L];
  if (total_P > 0.0)
    for (L = 1; L <= N; L++) p_L[L] /= total_P;

  /* mean_L */
  mean_L = 0.0;
  for (L = 1; L <= N; L++) mean_L += (double)L * p_L[L];

  /* var_L */
  var_L = 0.0;
  for (L = 1; L <= N; L++) var_L += ((double)L - mean_L) * ((double)L - mean_L) * p_L[L];

  /* KL(p_L || uniform) in nats. Python uses math.log (natural log). */
  /* Uniform: P_u(L) = (N - L + 1) * 2 / (N * (N + 1)) */
  kl = 0.0;
  for (L = 1; L <= N; L++) {
    if (p_L[L] > 0.0) {
      double p_u = 2.0 * (double)(N - L + 1) / ((double)N * (double)(N + 1));
      if (p_u > 0.0)
        kl += p_L[L] * log(p_L[L] / p_u);
    }
  }

  /* p_full_length: mass at L = N. Python computes:
   *   p_entry[1] * (1 - r)^(N-1)
   * which is the probability of entering at position 1 and reaching the end.
   */
  p_full = p_entry[1] * pow(1.0 - r, (double)(N - 1));

  feats[FAST_CAL_FEAT_mean_L_noss]      = mean_L;
  feats[FAST_CAL_FEAT_var_L_noss]       = var_L;
  feats[FAST_CAL_FEAT_KL_noss_to_unif]  = kl;
  feats[FAST_CAL_FEAT_p_full_length]    = p_full;

  free(p_entry);
  free(p_L);
  return eslOK;

 ERROR:
  if (p_entry) free(p_entry);
  if (p_L)     free(p_L);
  return eslEMEM;
}


/* extract_str_struct()
 * Port of Python struct_features(mp_log, ml_log, clen) from fast_cmcalibrate.py.
 *
 * Walks cm->ndtype[] to count MATP nodes and find MP_st / ML_st / MR_st
 * emission states. Converts cm->e[v] (probability form) to log-odds via
 * cm->null[]. Computes relative entropy moments.
 *
 * For each MATP node: find MP_st state (first state: v = cm->nodemap[nd]).
 *   Verify with cm->stid[v] == MATP_MP.
 *   16-vector: p_ab = e[v][ab]; lo_ab = log2(p_ab / (null[a] * null[b]))
 *   (a = ab/4, b = ab%4)
 *   Normalized emission weight: w_ab = (2^lo_ab) / 16, then normalize sum.
 *   rel_ent_v = sum_ab (w_ab / sum_w) * lo_ab
 *
 * For each MATL/MATR node: find ML_st / MR_st state.
 *   4-vector: p_a = e[v][a]; lo_a = log2(p_a / null[a])
 *   Normalized: w_a = (2^lo_a) * 0.25, then normalize.
 *   rel_ent_v = sum_a (w_a / sum_w) * lo_a
 */
static int
extract_str_struct(CM_t *cm, double *feats)
{
  int    nd, v;
  int    n_matp  = 0;
  double sum_mp_re = 0.0;
  double max_mp_re = -1e300;
  double sum_ml_re = 0.0;
  int    n_ml    = 0;

  for (nd = 0; nd < cm->nodes; nd++)
    {
      if (cm->ndtype[nd] == MATP_nd)
        {
          /* MP_st is the first state in a MATP node */
          v = cm->nodemap[nd];
          /* Safety check: should be MATP_MP */
          /* stid is char; MATP_MP = 6 */
          if (cm->stid[v] != MATP_MP) {
            /* skip if not what we expect (shouldn't happen) */
            continue;
          }
          /* 16-tuple log-odds */
          double lo[16];
          int ab;
          for (ab = 0; ab < 16; ab++) {
            int a = ab / 4, b = ab % 4;
            double p_ab = (double) cm->e[v][ab];
            double null_ab = (double)(cm->null[a] * cm->null[b]);
            /* Avoid log(0): guard with a tiny floor */
            if (p_ab <= 0.0 || null_ab <= 0.0)
              lo[ab] = -40.0;  /* effectively -inf in bits */
            else
              lo[ab] = log2(p_ab / null_ab);
          }
          /* Compute normalized weights w[ab] = 2^lo[ab] / 16 */
          double w[16];
          double sum_w = 0.0;
          for (ab = 0; ab < 16; ab++) {
            w[ab] = pow(2.0, lo[ab]) / 16.0;
            sum_w += w[ab];
          }
          /* Relative entropy */
          double re_v = 0.0;
          if (sum_w > 0.0) {
            for (ab = 0; ab < 16; ab++)
              re_v += (w[ab] / sum_w) * lo[ab];
          }
          n_matp++;
          sum_mp_re += re_v;
          if (re_v > max_mp_re) max_mp_re = re_v;
        }
      else if (cm->ndtype[nd] == MATL_nd || cm->ndtype[nd] == MATR_nd)
        {
          /* ML_st (MATL_ML=12) or MR_st (MATR_MR=15) is the first state */
          v = cm->nodemap[nd];
          /* The first state of a MATL node is ML_st, for MATR it's MR_st */
          /* 4-tuple log-odds */
          double lo[4];
          int a;
          for (a = 0; a < 4; a++) {
            double p_a    = (double) cm->e[v][a];
            double null_a = (double) cm->null[a];
            if (p_a <= 0.0 || null_a <= 0.0)
              lo[a] = -40.0;
            else
              lo[a] = log2(p_a / null_a);
          }
          /* Normalized weights: w[a] = 2^lo[a] * 0.25 */
          double w[4];
          double sum_w = 0.0;
          for (a = 0; a < 4; a++) {
            w[a] = pow(2.0, lo[a]) * 0.25;
            sum_w += w[a];
          }
          /* Relative entropy */
          double re_v = 0.0;
          if (sum_w > 0.0) {
            for (a = 0; a < 4; a++)
              re_v += (w[a] / sum_w) * lo[a];
          }
          sum_ml_re += re_v;
          n_ml++;
        }
    }

  /* Aggregate STR features */
  double pct_matp = (cm->clen > 0) ? (double)n_matp / (double)cm->clen : 0.0;
  double mean_mp  = (n_matp > 0) ? sum_mp_re / (double)n_matp : 0.0;
  double max_mp   = (n_matp > 0) ? max_mp_re : 0.0;
  double sum_mp   = sum_mp_re;
  double mean_ml  = (n_ml > 0) ? sum_ml_re / (double)n_ml : 0.0;

  feats[FAST_CAL_FEAT_n_matp]           = (double) n_matp;
  feats[FAST_CAL_FEAT_pct_matp]         = pct_matp;
  feats[FAST_CAL_FEAT_bp_density]       = pct_matp;   /* legacy alias */
  feats[FAST_CAL_FEAT_mean_matp_relent] = mean_mp;
  feats[FAST_CAL_FEAT_max_matp_relent]  = max_mp;
  feats[FAST_CAL_FEAT_sum_matp_relent]  = sum_mp;
  feats[FAST_CAL_FEAT_mean_ml_relent]   = mean_ml;

  return eslOK;
}


/* exact_score_aggregates()
 * Port of Python _exact_score_aggregates(means, vars_, N, pbegin, pend).
 *
 * Computes 8 aggregate statistics from per-position score mean/variance arrays.
 * Uses the same entry/exit model as fraglen_features.
 */
static void
exact_score_aggregates(double *means, double *vars_, int N,
                       double pbegin, double pend,
                       double *ret_mean_node_mean, double *ret_mean_node_var,
                       double *ret_ES_full,        double *ret_VarS_full,
                       double *ret_mean_ES,        double *ret_var_ES,
                       double *ret_mean_VarS,      double *ret_cov_L_ES)
{
  /* Cumulative sums: cs_m[k] = sum means[0..k-1], cs_v[k] = sum vars_[0..k-1] */
  double *cs_m  = NULL;
  double *cs_v  = NULL;
  double *p_entry = NULL;
  int i, j;
  double r;
  double total_P, E_ES, E_ES2, E_VarS, E_L, E_L_ES;
  double mean_ES, var_ES, mean_VarS, mean_L_w, cov_L_ES;

  cs_m    = (double *) malloc((N + 1) * sizeof(double));
  cs_v    = (double *) malloc((N + 1) * sizeof(double));
  p_entry = (double *) malloc((N + 1) * sizeof(double));

  if (!cs_m || !cs_v || !p_entry) goto ERROR;

  cs_m[0] = 0.0; cs_v[0] = 0.0;
  for (i = 0; i < N; i++) {
    cs_m[i + 1] = cs_m[i] + means[i];
    cs_v[i + 1] = cs_v[i] + vars_[i];
  }

  p_entry[0] = 0.0;
  p_entry[1] = 1.0 - pbegin;
  for (i = 2; i <= N; i++)
    p_entry[i] = pbegin / (double)(N > 1 ? (N - 1) : 1);

  r = pend / (double)(N > 1 ? (N - 1) : 1);

  total_P = 0.0;
  E_ES = E_ES2 = E_VarS = E_L = E_L_ES = 0.0;

  for (i = 1; i <= N; i++) {
    double p_e = p_entry[i];
    if (p_e == 0.0) continue;
    double reach = 1.0;
    for (j = i; j <= N; j++) {
      double w = p_e * reach * ((j < N) ? r : 1.0);
      /* Fragment [i-1, j-1] in 0-based positions: sum of means[i-1..j-1]
       * cs_m is 1-indexed prefix sums: cs_m[j] - cs_m[i-1]
       */
      double E_S_frag   = cs_m[j] - cs_m[i - 1];
      double Var_S_frag = cs_v[j] - cs_v[i - 1];
      double L          = (double)(j - i + 1);
      total_P += w;
      E_ES    += w * E_S_frag;
      E_ES2   += w * E_S_frag * E_S_frag;
      E_VarS  += w * Var_S_frag;
      E_L     += w * L;
      E_L_ES  += w * L * E_S_frag;
      reach *= (1.0 - r);
    }
  }

  if (total_P > 0.0) {
    mean_ES    = E_ES / total_P;
    var_ES     = E_ES2 / total_P - mean_ES * mean_ES;
    mean_VarS  = E_VarS / total_P;
    mean_L_w   = E_L / total_P;
    cov_L_ES   = E_L_ES / total_P - mean_L_w * mean_ES;
  } else {
    mean_ES = var_ES = mean_VarS = mean_L_w = cov_L_ES = 0.0;
  }

  /* Simple aggregates */
  {
    double sum_m = 0.0, sum_v = 0.0;
    for (i = 0; i < N; i++) { sum_m += means[i]; sum_v += vars_[i]; }
    *ret_mean_node_mean = (N > 0) ? sum_m / (double)N : 0.0;
    *ret_mean_node_var  = (N > 0) ? sum_v / (double)N : 0.0;
  }
  *ret_ES_full      = cs_m[N];
  *ret_VarS_full    = cs_v[N];
  *ret_mean_ES      = mean_ES;
  *ret_var_ES       = var_ES;
  *ret_mean_VarS    = mean_VarS;
  *ret_cov_L_ES     = cov_L_ES;

  free(cs_m); free(cs_v); free(p_entry);
  return;

 ERROR:
  if (cs_m)    free(cs_m);
  if (cs_v)    free(cs_v);
  if (p_entry) free(p_entry);
  /* Return zeros on allocation failure */
  *ret_mean_node_mean = *ret_mean_node_var = *ret_ES_full = *ret_VarS_full = 0.0;
  *ret_mean_ES = *ret_var_ES = *ret_mean_VarS = *ret_cov_L_ES = 0.0;
}


/* extract_c2_score_genomic()
 * Port of score_features_under_null(ml_log, GENOMIC_NULL, pbegin, pend, N) +
 * _exact_score_aggregates() from candidate_features.py / fast_cmcalibrate.py.
 *
 * Walks all ML_st and MR_st states (using cm->stid[v]).
 * For each such state, converts cm->e[v] (probability form, 4-vector)
 * to log-odds via cm->null[], then computes per-state score mean and variance
 * under the genomic null (0.269, 0.231, 0.230, 0.270).
 *
 * NOTE: Python's score_features_under_null uses N=len(ml) for STR CMs
 * (i.e., number of ML/MR emissions only), not clen. The _exact_score_aggregates
 * function uses N as the number of positions = number of ML/MR states.
 */
static int
extract_c2_score_genomic(CM_t *cm, double *feats)
{
  /* Genomic null: A=0.269, C=0.231, G=0.230, U=0.270 */
  static const double GENOMIC_NULL[4] = {0.269, 0.231, 0.230, 0.270};

  double pbegin = (double) cm->pbegin;
  double pend   = (double) cm->pend;
  int    v;
  int    n_ml   = 0;
  double *means = NULL;
  double *vars_ = NULL;
  int    n_alloc = cm->clen + 1;  /* upper bound */
  int    status;

  ESL_ALLOC(means, sizeof(double) * n_alloc);
  ESL_ALLOC(vars_,  sizeof(double) * n_alloc);

  /* Walk all states; collect ML_st and MR_st emit probabilities */
  for (v = 0; v < cm->M; v++) {
    if (cm->stid[v] == MATL_ML || cm->stid[v] == MATR_MR) {
      /* 4-tuple log-odds under cm->null */
      double lo[4];
      int a;
      for (a = 0; a < 4; a++) {
        double p_a    = (double) cm->e[v][a];
        double null_a = (double) cm->null[a];
        if (p_a <= 0.0 || null_a <= 0.0)
          lo[a] = -40.0;
        else
          lo[a] = log2(p_a / null_a);
      }
      /* per-state mean and variance under genomic null */
      double m = 0.0, m2 = 0.0;
      for (a = 0; a < 4; a++) {
        m  += GENOMIC_NULL[a] * lo[a];
        m2 += GENOMIC_NULL[a] * lo[a] * lo[a];
      }
          if (n_ml >= n_alloc) {
        /* shouldn't happen since n_alloc = clen+1, but be safe */
        n_alloc *= 2;
        ESL_REALLOC(means, sizeof(double) * n_alloc);
        ESL_REALLOC(vars_,  sizeof(double) * n_alloc);
      }
      means[n_ml] = m;
      vars_[n_ml] = m2 - m * m;
      n_ml++;
    }
  }

  if (n_ml == 0) {
    /* No ML/MR states — return zeros */
    feats[FAST_CAL_FEAT_mean_node_mean_g] = 0.0;
    feats[FAST_CAL_FEAT_mean_node_var_g]  = 0.0;
    feats[FAST_CAL_FEAT_ES_full_g]        = 0.0;
    feats[FAST_CAL_FEAT_VarS_full_g]      = 0.0;
    feats[FAST_CAL_FEAT_mean_ES_g]        = 0.0;
    feats[FAST_CAL_FEAT_var_ES_g]         = 0.0;
    feats[FAST_CAL_FEAT_mean_VarS_g]      = 0.0;
    feats[FAST_CAL_FEAT_cov_L_ES_g]       = 0.0;
  } else {
    double mn_mean, mn_var, es_full, vars_full, m_es, v_es, m_vars, c_l_es;
    exact_score_aggregates(means, vars_, n_ml, pbegin, pend,
                           &mn_mean, &mn_var, &es_full, &vars_full,
                           &m_es, &v_es, &m_vars, &c_l_es);
    feats[FAST_CAL_FEAT_mean_node_mean_g] = mn_mean;
    feats[FAST_CAL_FEAT_mean_node_var_g]  = mn_var;
    feats[FAST_CAL_FEAT_ES_full_g]        = es_full;
    feats[FAST_CAL_FEAT_VarS_full_g]      = vars_full;
    feats[FAST_CAL_FEAT_mean_ES_g]        = m_es;
    feats[FAST_CAL_FEAT_var_ES_g]         = v_es;
    feats[FAST_CAL_FEAT_mean_VarS_g]      = m_vars;
    feats[FAST_CAL_FEAT_cov_L_ES_g]       = c_l_es;
  }

  free(means);
  free(vars_);
  return eslOK;

 ERROR:
  if (means) free(means);
  if (vars_)  free(vars_);
  return eslEMEM;
}


/* =========================================================================
 * Phase 3 Feature Extraction — topo_fraglen_v2 and C1_OLD legacy
 */

/* build_node_subtree_spans()
 *
 * O(n) two-pass tree traversal ported from Python's _build_node_subtree_spans().
 *
 * use_consensus_rank=1: replace lpos/rpos alignment-col values with their
 *   rank in the sorted-unique set (consensus positions 1..clen).
 *   Required for topo_fraglen_v2 so noss CMs (MATL alignment-cols > clen)
 *   are not filtered out by the r > N guard.
 * use_consensus_rank=0: use raw alignment-col values (C1_OLD legacy).
 *
 * On entry:
 *   subtree_l[], subtree_r[] — caller-allocated int arrays, size cm->nodes.
 *   parent[]                — caller-allocated int array, size cm->nodes.
 *
 * On return, subtree_l[i] / subtree_r[i] are the left/right bounds of the
 * subtree rooted at node i (None → -1 in C).
 *
 * Returns eslOK on success, eslEMEM on allocation failure.
 */
static int
build_node_subtree_spans(CM_t *cm, int use_consensus_rank,
                         int *subtree_l, int *subtree_r, int *parent)
{
  int   n_nodes = cm->nodes;
  int   i, nd;
  int  *stk     = NULL;      /* stack of node indices */
  int   stk_top = -1;
  int   status;

  /* ---- consensus_rank_map (only when use_consensus_rank=1) -------------- */
  /* unique_col[k] = k-th unique alignment column from MATP/MATL/MATR nodes */
  int  *rank_lookup = NULL;  /* rank_lookup[acol] = consensus rank (1-based) */
  int   rank_ncols  = 0;     /* length of rank_lookup array                  */
  int  *unique_col  = NULL;
  int   n_unique    = 0;

  if (use_consensus_rank)
    {
      /* Step 1: collect unique alignment-col values from MATP/MATL/MATR.
       *
       * CMEmitMap lpos/rpos semantics:
       *   MATP: lpos = consensus pos of left emission; rpos = right emission.
       *   MATL: lpos = consensus pos of emission; rpos = non-inclusive bound (skip).
       *   MATR: rpos = consensus pos of emission; lpos = non-inclusive bound (skip).
       * So "has valid lpos" iff ndtype is MATP or MATL.
       *    "has valid rpos" iff ndtype is MATP or MATR.
       *
       * cm->map[k] converts consensus pos k to alignment column.
       */
      int n_alloc_u = n_nodes * 2 + 2;
      ESL_ALLOC(unique_col, sizeof(int) * n_alloc_u);

      for (nd = 0; nd < n_nodes; nd++)
        {
          int has_lpos = (cm->ndtype[nd] == MATP_nd || cm->ndtype[nd] == MATL_nd);
          int has_rpos = (cm->ndtype[nd] == MATP_nd || cm->ndtype[nd] == MATR_nd);
          if (!has_lpos && !has_rpos) continue;

          if (has_lpos)
            {
              int lp   = cm->emap->lpos[nd];
              int acol = (lp >= 1 && lp <= cm->clen) ? cm->map[lp] : 0;
              if (acol > 0)
                {
                  int dup = 0, j2;
                  for (j2 = 0; j2 < n_unique; j2++)
                    if (unique_col[j2] == acol) { dup = 1; break; }
                  if (!dup)
                    {
                      if (n_unique >= n_alloc_u) {
                        n_alloc_u *= 2;
                        ESL_REALLOC(unique_col, sizeof(int) * n_alloc_u);
                      }
                      unique_col[n_unique++] = acol;
                    }
                }
            }
          if (has_rpos)
            {
              int rp   = cm->emap->rpos[nd];
              int acol = (rp >= 1 && rp <= cm->clen) ? cm->map[rp] : 0;
              if (acol > 0)
                {
                  int dup = 0, j2;
                  for (j2 = 0; j2 < n_unique; j2++)
                    if (unique_col[j2] == acol) { dup = 1; break; }
                  if (!dup)
                    {
                      if (n_unique >= n_alloc_u) {
                        n_alloc_u *= 2;
                        ESL_REALLOC(unique_col, sizeof(int) * n_alloc_u);
                      }
                      unique_col[n_unique++] = acol;
                    }
                }
            }
        }

      /* Step 2: sort unique_col ascending (insertion sort; n_unique <= clen) */
      {
        int j2, k2, tmp2;
        for (j2 = 1; j2 < n_unique; j2++)
          {
            tmp2 = unique_col[j2];
            for (k2 = j2 - 1; k2 >= 0 && unique_col[k2] > tmp2; k2--)
              unique_col[k2 + 1] = unique_col[k2];
            unique_col[k2 + 1] = tmp2;
          }
      }

      /* Step 3: build direct lookup array: alignment_col → rank (1-indexed).
       * max alignment column = unique_col[n_unique-1].
       */
      rank_ncols = (n_unique > 0) ? unique_col[n_unique - 1] + 1 : 1;
      ESL_ALLOC(rank_lookup, sizeof(int) * rank_ncols);
      for (i = 0; i < rank_ncols; i++) rank_lookup[i] = -1;  /* -1 = not ranked */
      for (i = 0; i < n_unique; i++)
        rank_lookup[unique_col[i]] = i + 1;   /* 1-indexed rank */
    }

  /* ---- allocate stack and DFS order array -------------------------------- */
  ESL_ALLOC(stk, sizeof(int) * (n_nodes + 1));

  /* Build DFS pre-order: sort nodes by cm->nodemap[nd] (first state index).
   * Infernal node labels are NOT in DFS file-order for nested BIFs: BEGL
   * subtrees get lower labels but appear AFTER BEGR subtrees in the file.
   * The parent-stack algorithm requires DFS pre-order to assign correct parents.
   */
  {
    int *dfs_order = NULL;
    int  j2, tmp2;
    ESL_ALLOC(dfs_order, sizeof(int) * n_nodes);
    for (i = 0; i < n_nodes; i++) dfs_order[i] = i;
    /* Insertion sort by cm->nodemap[nd] (n_nodes ≤ a few thousand) */
    for (i = 1; i < n_nodes; i++) {
      tmp2 = dfs_order[i];
      for (j2 = i - 1; j2 >= 0 && cm->nodemap[dfs_order[j2]] > cm->nodemap[tmp2]; j2--)
        dfs_order[j2 + 1] = dfs_order[j2];
      dfs_order[j2 + 1] = tmp2;
    }

    /* ======== Pass 1: DFS pre-order walk — build parent[] and init spans == */
    for (i = 0; i < n_nodes; i++) parent[i] = -1;

    for (i = 0; i < n_nodes; i++)
      {
        nd = dfs_order[i];   /* node label in DFS pre-order */

        /* record parent from top of stack */
        if (stk_top >= 0)
          parent[nd] = stk[stk_top];

        /* initialize own subtree span from this node's lpos/rpos */
        int l, r;
        {
          int has_lpos = (cm->ndtype[nd] == MATP_nd || cm->ndtype[nd] == MATL_nd);
          int has_rpos = (cm->ndtype[nd] == MATP_nd || cm->ndtype[nd] == MATR_nd);

          if (use_consensus_rank)
            {
              int acol_l = 0, acol_r = 0;
              if (has_lpos) {
                int lp = cm->emap->lpos[nd];
                acol_l = (lp >= 1 && lp <= cm->clen) ? cm->map[lp] : 0;
              }
              if (has_rpos) {
                int rp = cm->emap->rpos[nd];
                acol_r = (rp >= 1 && rp <= cm->clen) ? cm->map[rp] : 0;
              }
              l = (acol_l > 0 && acol_l < rank_ncols && rank_lookup[acol_l] >= 0) ? rank_lookup[acol_l] : -1;
              r = (acol_r > 0 && acol_r < rank_ncols && rank_lookup[acol_r] >= 0) ? rank_lookup[acol_r] : -1;
            }
          else
            {
              /* C1_OLD: use raw alignment-column values */
              int acol_l = 0, acol_r = 0;
              if (has_lpos) {
                int lp = cm->emap->lpos[nd];
                acol_l = (lp >= 1 && lp <= cm->clen) ? cm->map[lp] : 0;
              }
              if (has_rpos) {
                int rp = cm->emap->rpos[nd];
                acol_r = (rp >= 1 && rp <= cm->clen) ? cm->map[rp] : 0;
              }
              l = (acol_l > 0) ? acol_l : -1;
              r = (acol_r > 0) ? acol_r : -1;
            }
        }

        /* _build_node_subtree_spans (v2) normalizes single-sided nodes so MATL/MATR
         * are included as candidates (l=r=their one position).
         * topo_fraglen_features (C1_OLD) does NOT apply this normalization.
         */
        if (use_consensus_rank) {
          if (l == -1 && r != -1) l = r;
          if (r == -1 && l != -1) r = l;
        }

        subtree_l[nd] = l;
        subtree_r[nd] = r;

        /* stack management: push nd (node label) so parent[] gets node labels */
        switch (cm->ndtype[nd])
          {
          case ROOT_nd:
          case MATL_nd:
          case MATR_nd:
          case MATP_nd:
          case BIF_nd:
          case BEGL_nd:
          case BEGR_nd:
            stk[++stk_top] = nd;
            break;
          case END_nd:
            /* pop back to most recent BEGL/BEGR (or ROOT) */
            while (stk_top >= 0 &&
                   cm->ndtype[stk[stk_top]] != BEGL_nd &&
                   cm->ndtype[stk[stk_top]] != BEGR_nd &&
                   cm->ndtype[stk[stk_top]] != ROOT_nd)
              stk_top--;
            /* if top is BEGL or BEGR, pop it too */
            if (stk_top >= 0 &&
                (cm->ndtype[stk[stk_top]] == BEGL_nd ||
                 cm->ndtype[stk[stk_top]] == BEGR_nd))
              stk_top--;
            break;
          default:
            break;
          }
      }
    free(dfs_order);
  }

  /* ======== Pass 2: post-order (reverse) — propagate spans up to parent === */
  for (i = n_nodes - 1; i >= 0; i--)
    {
      int p = parent[i];
      if (p < 0) continue;
      int li = subtree_l[i];
      int ri = subtree_r[i];
      if (li != -1 && (subtree_l[p] == -1 || li < subtree_l[p]))
        subtree_l[p] = li;
      if (ri != -1 && (subtree_r[p] == -1 || ri > subtree_r[p]))
        subtree_r[p] = ri;
    }

  free(stk);
  if (rank_lookup) free(rank_lookup);
  if (unique_col)  free(unique_col);
  return eslOK;

 ERROR:
  if (stk)         free(stk);
  if (rank_lookup) free(rank_lookup);
  if (unique_col)  free(unique_col);
  return eslEMEM;
}


/* summarize_distribution()
 *
 * Given a discrete distribution p_L[] (1-indexed, length N, already normalized),
 * compute the 4 summary features.
 *
 * KL uses natural log (matching Python's math.log).
 * p_full_length = p_L[N] (mass at L = N, passed as p_L_N directly since the
 *   caller has already restricted the array to p_L[1..N] with p_L[0] unused).
 */
static void
summarize_distribution(double *p_L, int N,
                       double *ret_mean_L, double *ret_var_L,
                       double *ret_KL,    double *ret_p_full)
{
  int    L;
  double mean_L = 0.0, var_L = 0.0, kl = 0.0;
  double denom_u = 2.0 / ((double)N * (double)(N + 1));

  for (L = 1; L <= N; L++) mean_L += (double)L * p_L[L];
  for (L = 1; L <= N; L++) var_L  += ((double)L - mean_L) * ((double)L - mean_L) * p_L[L];
  for (L = 1; L <= N; L++) {
    if (p_L[L] > 0.0) {
      double p_u = (double)(N - L + 1) * denom_u;
      if (p_u > 0.0)
        kl += p_L[L] * log(p_L[L] / p_u);
    }
  }

  *ret_mean_L = mean_L;
  *ret_var_L  = var_L;
  *ret_KL     = kl;
  *ret_p_full = p_L[N];
}


/* extract_topo_noend_basic()
 *
 * Port of Python topo_fraglen_v2(parsed, include_end=False, rich=False, prefix="noend_").
 * Computes 4 features: noend_mean_L, noend_var_L, noend_KL_to_unif, noend_p_full_length.
 *
 * Uses build_node_subtree_spans(use_consensus_rank=1) so that NOSS CMs
 * (whose MATL alignment-columns can exceed clen) get properly ranked.
 *
 * Degenerate case (n_begin == 0 or N <= 1): sets all 4 features to NaN.
 */
static int
extract_topo_noend_basic(CM_t *cm, double *feats)
{
  int     N      = cm->clen;
  double  pbegin = (double) cm->pbegin;
  int    *subtree_l = NULL;
  int    *subtree_r = NULL;
  int    *parent    = NULL;
  double *p_L       = NULL;
  int     status;
  int     nd, L;
  double  mass;

  if (N <= 1) {
    feats[FAST_CAL_FEAT_noend_mean_L]        = 0.0 / 0.0;   /* NaN */
    feats[FAST_CAL_FEAT_noend_var_L]         = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_KL_to_unif]    = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_p_full_length] = 0.0 / 0.0;
    return eslOK;
  }

  ESL_ALLOC(subtree_l, sizeof(int) * cm->nodes);
  ESL_ALLOC(subtree_r, sizeof(int) * cm->nodes);
  ESL_ALLOC(parent,    sizeof(int) * cm->nodes);
  ESL_ALLOC(p_L,       sizeof(double) * (N + 2));

  status = build_node_subtree_spans(cm, /*use_consensus_rank=*/1,
                                    subtree_l, subtree_r, parent);
  if (status != eslOK) goto ERROR;

  /* Collect valid local-begin candidates: MATP/MATR/MATL/BIF nodes
   * with both subtree_l and subtree_r defined and within [1..N].
   * (Matches Python: VALID_BEGIN_NODE_TYPES = MATP, MATR, MATL, BIF)
   */
  typedef struct { int l; int r; } cand_t;
  cand_t *cands   = NULL;
  int     n_cands = 0;
  int     c_alloc = cm->nodes;
  ESL_ALLOC(cands, sizeof(cand_t) * c_alloc);

  for (nd = 0; nd < cm->nodes; nd++)
    {
      if (cm->ndtype[nd] != MATP_nd &&
          cm->ndtype[nd] != MATR_nd &&
          cm->ndtype[nd] != MATL_nd &&
          cm->ndtype[nd] != BIF_nd) continue;
      int sl = subtree_l[nd];
      int sr = subtree_r[nd];
      if (sl == -1 || sr == -1) continue;
      if (sl < 1 || sr > N || sl > sr) continue;
      cands[n_cands].l = sl;
      cands[n_cands].r = sr;
      n_cands++;
    }

  if (n_cands == 0) {
    /* Degenerate CM: all 4 features = NaN */
    feats[FAST_CAL_FEAT_noend_mean_L]        = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_var_L]         = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_KL_to_unif]    = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_p_full_length] = 0.0 / 0.0;
    free(cands); free(subtree_l); free(subtree_r); free(parent); free(p_L);
    return eslOK;
  }

  /* Build P(L) for include_end=False:
   *   p_L[N] += (1 - pbegin)            (full-length mass)
   *   for each (l, r) in cands: p_L[r - l + 1] += pbegin / n_cands
   */
  for (L = 0; L <= N + 1; L++) p_L[L] = 0.0;
  p_L[N] += (1.0 - pbegin);
  {
    double x = pbegin / (double) n_cands;
    int ci;
    for (ci = 0; ci < n_cands; ci++)
      {
        L = cands[ci].r - cands[ci].l + 1;
        if (L >= 1 && L <= N)
          p_L[L] += x;
      }
  }

  /* Restrict to [1..N] and normalize */
  mass = 0.0;
  for (L = 1; L <= N; L++) mass += p_L[L];

  if (mass <= 0.0) {
    feats[FAST_CAL_FEAT_noend_mean_L]        = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_var_L]         = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_KL_to_unif]    = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_noend_p_full_length] = 0.0 / 0.0;
    free(cands); free(subtree_l); free(subtree_r); free(parent); free(p_L);
    return eslOK;
  }
  for (L = 1; L <= N; L++) p_L[L] /= mass;

  /* Summarize */
  {
    double mean_L, var_L, kl, p_full;
    summarize_distribution(p_L, N, &mean_L, &var_L, &kl, &p_full);
    feats[FAST_CAL_FEAT_noend_mean_L]        = mean_L;
    feats[FAST_CAL_FEAT_noend_var_L]         = var_L;
    feats[FAST_CAL_FEAT_noend_KL_to_unif]    = kl;
    feats[FAST_CAL_FEAT_noend_p_full_length] = p_full;
  }

  free(cands);
  free(subtree_l);
  free(subtree_r);
  free(parent);
  free(p_L);
  return eslOK;

 ERROR:
  if (cands)     free(cands);
  if (subtree_l) free(subtree_l);
  if (subtree_r) free(subtree_r);
  if (parent)    free(parent);
  if (p_L)       free(p_L);
  return eslEMEM;
}


/* extract_c1_old()
 *
 * Port of Python topo_fraglen_features(parsed) — the C1_OLD legacy feature set.
 * Differs from extract_topo_noend_basic() in three ways:
 *   1. Uses build_node_subtree_spans(use_consensus_rank=0): raw alignment-col values.
 *   2. Valid begins: all non-(ROOT/END) nodes with both l and r defined and
 *      1 <= l, r <= N, l <= r.  (NOT the strict MATP/MATR/MATL/BIF filter.)
 *   3. Fallback: if no valid begins, falls back to noss-fraglen
 *      (reusing extract_noss_fraglen).
 *
 * Produces: mean_L_str, var_L_str, KL_str_to_unif (no p_full_length).
 * KL uses natural log.
 */
static int
extract_c1_old(CM_t *cm, double *feats)
{
  int     N      = cm->clen;
  double  pbegin = (double) cm->pbegin;
  int    *subtree_l = NULL;
  int    *subtree_r = NULL;
  int    *parent    = NULL;
  double *p_L       = NULL;
  int     nd, L, status;
  double  mass;

  if (N <= 1) {
    /* Python returns NaN for N<=1 (clen <= 1).
     * We mirror topo_fraglen_features's behavior:
     * it checks N <= 1 and returns NaN dict. */
    feats[FAST_CAL_FEAT_mean_L_str]    = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_var_L_str]     = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_KL_str_to_unif] = 0.0 / 0.0;
    return eslOK;
  }

  ESL_ALLOC(subtree_l, sizeof(int) * cm->nodes);
  ESL_ALLOC(subtree_r, sizeof(int) * cm->nodes);
  ESL_ALLOC(parent,    sizeof(int) * cm->nodes);
  ESL_ALLOC(p_L,       sizeof(double) * (N + 2));

  status = build_node_subtree_spans(cm, /*use_consensus_rank=*/0,
                                    subtree_l, subtree_r, parent);
  if (status != eslOK) goto ERROR;

  /* Collect candidates: all non-(ROOT/END) nodes with both l,r defined
   * and satisfying 1 <= l <= r <= N.
   * Python: "nodes other than ROOT/END with both lpos and rpos in their
   *  subtree span. We collect (l, r) pairs."
   * Filter: "if l < 1 or r > N or l > r: continue"
   */
  typedef struct { int l; int r; } cand2_t;
  cand2_t *cands   = NULL;
  int      n_cands = 0;
  int      c_alloc = cm->nodes;
  ESL_ALLOC(cands, sizeof(cand2_t) * c_alloc);

  for (nd = 0; nd < cm->nodes; nd++)
    {
      if (cm->ndtype[nd] == ROOT_nd || cm->ndtype[nd] == END_nd) continue;
      int sl = subtree_l[nd];
      int sr = subtree_r[nd];
      if (sl == -1 || sr == -1) continue;
      if (sl < 1 || sr > N || sl > sr) continue;
      cands[n_cands].l = sl;
      cands[n_cands].r = sr;
      n_cands++;
    }

  if (n_cands == 0) {
    /* Fallback to noss-style fraglen */
    double tmp_feats[FAST_CAL_NFEAT_PHASE2];
    int    fstatus;
    fstatus = extract_noss_fraglen(cm, tmp_feats);
    feats[FAST_CAL_FEAT_mean_L_str]    = tmp_feats[FAST_CAL_FEAT_mean_L_noss];
    feats[FAST_CAL_FEAT_var_L_str]     = tmp_feats[FAST_CAL_FEAT_var_L_noss];
    feats[FAST_CAL_FEAT_KL_str_to_unif] = tmp_feats[FAST_CAL_FEAT_KL_noss_to_unif];
    free(cands); free(subtree_l); free(subtree_r); free(parent); free(p_L);
    return fstatus;
  }

  /* Build P(L): same as v2 (include_end=False) */
  for (L = 0; L <= N + 1; L++) p_L[L] = 0.0;
  p_L[N] += (1.0 - pbegin);
  {
    double x = pbegin / (double) n_cands;
    int ci;
    for (ci = 0; ci < n_cands; ci++)
      {
        L = cands[ci].r - cands[ci].l + 1;
        if (L >= 1 && L <= N)
          p_L[L] += x;
      }
  }

  /* Restrict and normalize */
  mass = 0.0;
  for (L = 1; L <= N; L++) mass += p_L[L];

  if (mass <= 0.0) {
    feats[FAST_CAL_FEAT_mean_L_str]    = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_var_L_str]     = 0.0 / 0.0;
    feats[FAST_CAL_FEAT_KL_str_to_unif] = 0.0 / 0.0;
    free(cands); free(subtree_l); free(subtree_r); free(parent); free(p_L);
    return eslOK;
  }
  for (L = 1; L <= N; L++) p_L[L] /= mass;

  /* Summarize (C1_OLD only has 3 outputs — no p_full_length) */
  {
    double mean_L, var_L, kl, p_full;
    summarize_distribution(p_L, N, &mean_L, &var_L, &kl, &p_full);
    feats[FAST_CAL_FEAT_mean_L_str]     = mean_L;
    feats[FAST_CAL_FEAT_var_L_str]      = var_L;
    feats[FAST_CAL_FEAT_KL_str_to_unif] = kl;
  }

  free(cands);
  free(subtree_l);
  free(subtree_r);
  free(parent);
  free(p_L);
  return eslOK;

 ERROR:
  if (cands)     free(cands);
  if (subtree_l) free(subtree_l);
  if (subtree_r) free(subtree_r);
  if (parent)    free(parent);
  if (p_L)       free(p_L);
  return eslEMEM;
}


/* cm_FastCalibrate_ExtractFeatures()
 * Fill feats[0..FAST_CAL_NFEAT-1] from cm (all 27 features).
 * Returns eslOK on success, eslFAIL/eslEMEM on error.
 */
int
cm_FastCalibrate_ExtractFeatures(CM_t *cm, double *feats)
{
  int status;

  if ((status = extract_clen(cm, feats))              != eslOK) return status;
  if ((status = extract_noss_fraglen(cm, feats))      != eslOK) return status;
  if ((status = extract_str_struct(cm, feats))        != eslOK) return status;
  if ((status = extract_c2_score_genomic(cm, feats))  != eslOK) return status;
  if ((status = extract_topo_noend_basic(cm, feats))  != eslOK) return status;
  if ((status = extract_c1_old(cm, feats))            != eslOK) return status;

  return eslOK;
}


/* cm_FastCalibrate_PrintModels()
 * Dump all loaded ridges to <fp> in a format suitable for diffing against
 * the source JSONs. Triggers lazy load on first call.
 * Returns eslOK on success, eslFAIL on load error.
 */
int
cm_FastCalibrate_PrintModels(FILE *fp)
{
  static const char *bucket_names[N_BUCKETS] = {"tiny","small","medlarge","large","huge"};
  static const char *mode_names  [N_MODES]   = {"ECMLC","ECMLI","ECMGC","ECMGI"};
  static const char *target_labels[6] = {
    "STR_lambda", "STR_mu_extrap", "STR_mu_orig",
    "NOSS_lambda","NOSS_mu_extrap","NOSS_mu_orig"
  };
  FastCalRidge (*tables[6])[N_MODES] = {
    g_models.str_lambda,    g_models.str_mu_extrap, g_models.str_mu_orig,
    g_models.noss_lambda,   g_models.noss_mu_extrap,g_models.noss_mu_orig
  };

  int status;
  int t, b, m, i;

  if ((status = load_models()) != eslOK) return status;

  fprintf(fp, "# cm_fast_calibrate models dump\n");
  fprintf(fp, "# models_version: %s\n", g_models.models_version);

  for (t = 0; t < 6; t++)
    for (b = 0; b < N_BUCKETS; b++)
      for (m = 0; m < N_MODES; m++)
        {
          FastCalRidge *r = &tables[t][b][m];
          if (r->nfeat == 0) continue;  /* empty slot */

          fprintf(fp, "\n[%s][%s][%s]\n", target_labels[t], bucket_names[b], mode_names[m]);
          fprintf(fp, "  nfeat:      %d\n", r->nfeat);
          fprintf(fp, "  intercept:  %.10f\n", r->intercept);
          fprintf(fp, "  loo_mse:    %.10f\n", r->loo_mse);
          for (i = 0; i < r->nfeat; i++)
            fprintf(fp, "  feat[%2d]  %-30s  mean=%.10f  std=%.10f  coef=%.10f\n",
                    i, r->fnames[i], r->mean[i], r->std[i], r->coef[i]);
        }

  return eslOK;
}
