#!/bin/bash
# embed_fastcal_models.sh
# Embed the production JSON model files into a C header as unsigned char arrays.
# Usage: embed_fastcal_models.sh <outfile>
# The JSONs are tracked in src/cm_fast_calibrate_data/ (brief 26_0422-104).
# v5.5: added v55_tiny_models.json, v55_K_tiny_models.json,
#        v55_small_models.json, v55_K_small_models.json.
# brief 22: added v55_{medlarge,large,huge}_models.json and matching K JSONs.
# brief 46: added v55_noss_hybrid_production.json (replaces NOSS half of
#           production_models_v42_noss + production_mu_models_v42_noss +
#           v4x_K_ridge_noss in the load path; those 3 JSONs removed from
#           the embed array — they are archived on disk only).
# brief 67: added v55_atrich_tiny_models.json + v55_atrich_small_models.json
#           (Option-E gated AT-rich predictor, 7 CV-firmed cells; STR tiny/small
#           only, gated on corrected gc_emit <= 0.45).
# brief 74: added the 7 ere predictor JSONs (ere_predictor_{tiny,small,medlarge,
#           large,huge}_str.json + {tiny,small}_noss.json). NAIVE ridge for the
#           --ere/--enone dispatch path (default --eent path is UNCHANGED). Same
#           v5.5 feature pool as C0 (brief-073 ablation: ere-axis feats redundant
#           and dropped), so no new C feature computation. 104 deployed cells;
#           huge-glocal STR + NOSS medlarge/large/huge fall back to C0.
# brief 26_0422-091: removed production_models_v41.json, production_models_
#           v42_largehuge.json, and v4x_K_ridge_str.json from the embed array.
#           All three are dead — v5.5 STR lambda/K load first and fill every
#           slot via skip-if-already-filled guards, so the v4.1/v4.2/K-ridge
#           lambda+K loaders never win. production_mu_models_v41.json and
#           production_mu_models_v42_largehuge.json are KEPT: v5.5 never loads
#           "mu_orig" (only "lambda"/"mu_extrap"), so those two files remain
#           the sole live source of g_models.str_mu_orig[bucket][mode], which
#           feeds SetExpInfo()'s mu_orig argument directly.

set -e

OUTFILE="${1:-cm_fast_calibrate_models.h}"

JSON_DIR="$(dirname "$0")/cm_fast_calibrate_data"

JSONS=(
  "${JSON_DIR}/v55_tiny_models.json"
  "${JSON_DIR}/v55_K_tiny_models.json"
  "${JSON_DIR}/v55_small_models.json"
  "${JSON_DIR}/v55_K_small_models.json"
  "${JSON_DIR}/v55_medlarge_models.json"
  "${JSON_DIR}/v55_K_medlarge_models.json"
  "${JSON_DIR}/v55_large_models.json"
  "${JSON_DIR}/v55_K_large_models.json"
  "${JSON_DIR}/v55_huge_models.json"
  "${JSON_DIR}/v55_K_huge_models.json"
  "${JSON_DIR}/production_mu_models_v41.json"
  "${JSON_DIR}/production_mu_models_v42_largehuge.json"
  "${JSON_DIR}/v55_noss_hybrid_production.json"
  "${JSON_DIR}/v55_atrich_tiny_models.json"
  "${JSON_DIR}/v55_atrich_small_models.json"
  "${JSON_DIR}/ere_predictor_tiny_str.json"
  "${JSON_DIR}/ere_predictor_small_str.json"
  "${JSON_DIR}/ere_predictor_medlarge_str.json"
  "${JSON_DIR}/ere_predictor_large_str.json"
  "${JSON_DIR}/ere_predictor_huge_str.json"
  "${JSON_DIR}/ere_predictor_tiny_noss.json"
  "${JSON_DIR}/ere_predictor_small_noss.json"
)

# Verify all JSONs are accessible
for f in "${JSONS[@]}"; do
  if [ ! -r "$f" ]; then
    echo "ERROR: Cannot read JSON file: $f" >&2
    exit 1
  fi
done

# Compute SHA-256 hash of concatenated JSON content
HASH=$(cat "${JSONS[@]}" | sha256sum | awk '{print $1}')

TMPFILE="${OUTFILE}.tmp.$$"

cat > "${TMPFILE}" << HEADER
/* cm_fast_calibrate_models.h
 * AUTO-GENERATED by embed_fastcal_models.sh — DO NOT EDIT BY HAND.
 * Embeds the 25 production JSON model files as C char arrays.
 * Rebuild with: make cm_fast_calibrate_models.h
 */
#ifndef cm_FAST_CALIBRATE_MODELS_INCLUDED
#define cm_FAST_CALIBRATE_MODELS_INCLUDED

/* SHA-256 of the concatenated content of all 25 production JSON files.
 * Used by the regression harness to detect stale expected-output TSVs.
 */
static const char fast_cal_models_version[] = "${HASH}";

HEADER

# Embed each JSON file as a C byte array, in xxd -i's variable-naming and
# array-content convention (varname = path with every non-alnum char, incl.
# leading "./", turned into '_'), but using od instead of xxd: od is POSIX
# (coreutils), xxd ships with vim and is not reliably present on a git-only
# build machine.
for f in "${JSONS[@]}"; do
  varname=$(printf '%s' "$f" | sed 's/[^A-Za-z0-9]/_/g')
  nbytes=$(wc -c < "$f" | tr -d ' ')
  bytes=$(od -An -v -tx1 "$f" | tr -s ' \n' '\n' | sed '/^$/d;s/^/0x/;s/$/,/' | \
            paste -sd' ' - | fold -s -w 76)

  # Self-check: the emitted array must hold exactly ${nbytes} elements.
  #
  # od's output formatting (column width, line wrapping) differs across
  # implementations -- GNU coreutils vs BSD/macOS vs busybox. The `tr -s`
  # normalization above is deliberately written to absorb that, but if it ever
  # failed to, the corruption would be SILENT: C infers an array's size from
  # its initializer, so a dropped or duplicated byte would simply disagree
  # with ${varname}_len (computed independently by wc -c above) and the loader
  # would read a wrong-length buffer at runtime. No compiler error, no crash,
  # just quietly wrong model data. Counting commas is POSIX (unlike grep -o)
  # and turns that whole class of portability failure into a loud build stop.
  nemit=$(printf '%s' "${bytes}" | tr -cd ',' | wc -c | tr -d ' ')
  if [ "${nemit}" -ne "${nbytes}" ]; then
    echo "ERROR: ${f}: embedded ${nemit} bytes but file is ${nbytes} bytes." >&2
    echo "       od output was not parsed as expected on this platform." >&2
    echo "       (od: $(od --version 2>/dev/null | head -1 || echo 'unknown'))" >&2
    exit 1
  fi

  {
    echo "static const unsigned char ${varname}[] = {"
    printf '%s\n' "${bytes}"
    echo "};"
    echo "static const unsigned int ${varname}_len = ${nbytes};"
  } >> "${TMPFILE}"
  echo "" >> "${TMPFILE}"
done

echo "#endif /* cm_FAST_CALIBRATE_MODELS_INCLUDED */" >> "${TMPFILE}"

mv "${TMPFILE}" "${OUTFILE}"
echo "Generated: ${OUTFILE} (models_version=${HASH})"
