#!/bin/bash
# embed_fastcal_models.sh
# Embed the production JSON model files into a C header as unsigned char arrays.
# Usage: embed_fastcal_models.sh <outfile>
# The JSON paths are absolute and reference the notebook analysis directory.
# Do NOT commit copies of the JSONs into the Infernal repo.
# v5.5: added v55_tiny_models.json, v55_K_tiny_models.json,
#        v55_small_models.json, v55_K_small_models.json.
# brief 22: added v55_{medlarge,large,huge}_models.json and matching K JSONs.
# brief 46: added v55_noss_hybrid_production.json (replaces NOSS half of
#           production_models_v42_noss + production_mu_models_v42_noss +
#           v4x_K_ridge_noss in the load path; those 3 JSONs removed from
#           the embed array — they are archived on disk only).
# brief 67: added v55_atrich_tiny_models.json + v55_atrich_small_models.json
#           (Option-E gated AT-rich predictor, 7 CV-firmed cells; STR tiny/small
#           only, gated on corrected gc_emit <= 0.45).

set -e

OUTFILE="${1:-cm_fast_calibrate_models.h}"

JSON_DIR="$(dirname "$0")/cm_fast_calibrate_data"

JSONS=(
  "${JSON_DIR}/v55_tiny_models.json"
  "${JSON_DIR}/v55_K_tiny_models.json"
  "${JSON_DIR}/v55_small_models.json"
  "${JSON_DIR}/v55_K_small_models.json"
  "${JSON_DIR}/v55_medlarge_models.json"
  "${JSON_DIR}/v55_K_medlarge_models.json"
  "${JSON_DIR}/v55_large_models.json"
  "${JSON_DIR}/v55_K_large_models.json"
  "${JSON_DIR}/v55_huge_models.json"
  "${JSON_DIR}/v55_K_huge_models.json"
  "${JSON_DIR}/production_models_v41.json"
  "${JSON_DIR}/production_mu_models_v41.json"
  "${JSON_DIR}/production_models_v42_largehuge.json"
  "${JSON_DIR}/production_mu_models_v42_largehuge.json"
  "${JSON_DIR}/v4x_K_ridge_str.json"
  "${JSON_DIR}/v55_noss_hybrid_production.json"
  "${JSON_DIR}/v55_atrich_tiny_models.json"
  "${JSON_DIR}/v55_atrich_small_models.json"
)

# Verify all JSONs are accessible
for f in "${JSONS[@]}"; do
  if [ ! -r "$f" ]; then
    echo "ERROR: Cannot read JSON file: $f" >&2
    exit 1
  fi
done

# Compute SHA-256 hash of concatenated JSON content
HASH=$(cat "${JSONS[@]}" | sha256sum | awk '{print $1}')

TMPFILE="${OUTFILE}.tmp.$$"

cat > "${TMPFILE}" << HEADER
/* cm_fast_calibrate_models.h
 * AUTO-GENERATED by embed_fastcal_models.sh — DO NOT EDIT BY HAND.
 * Embeds the 20 production JSON model files as C char arrays.
 * Rebuild with: make cm_fast_calibrate_models.h
 */
#ifndef cm_FAST_CALIBRATE_MODELS_INCLUDED
#define cm_FAST_CALIBRATE_MODELS_INCLUDED

/* SHA-256 of the concatenated content of all 20 production JSON files.
 * Used by the regression harness to detect stale expected-output TSVs.
 */
static const char fast_cal_models_version[] = "${HASH}";

HEADER

# Embed each JSON file using xxd -i
for f in "${JSONS[@]}"; do
  basename_noext=$(basename "$f" .json | tr '-' '_')
  # xxd -i produces: unsigned char varname[] = {...}; unsigned int varname_len = N;
  # We want static const unsigned char varname[] = {...};
  # Transform: prepend "static const " to the unsigned char line, and add const to len
  xxd -i "$f" | sed \
    -e 's/^unsigned char /static const unsigned char /g' \
    -e 's/^unsigned int /static const unsigned int /g' \
    >> "${TMPFILE}"
  echo "" >> "${TMPFILE}"
done

echo "#endif /* cm_FAST_CALIBRATE_MODELS_INCLUDED */" >> "${TMPFILE}"

mv "${TMPFILE}" "${OUTFILE}"
echo "Generated: ${OUTFILE} (models_version=${HASH})"
